### ISSUE TITLE
Home directory is absolute

### ISSUE THREAD

**Issue by mikedfunk** [zbirenbaum/copilot.lua#1]
https://github.com/zbirenbaum/copilot.lua/blob/178fc2baa80eae7004d8dde835109101143486d6/lua/copilot/setup.lua#L38

![image](https://user-images.githubusercontent.com/661038/161640590-074a1825-aac7-45a1-9103-505bed7c333e.png)

**Comment by zbirenbaum** [comment]
oops one sec

**Comment by zbirenbaum** [comment]
Should be fixed. Packersync and let me know if it works.

**Comment by mikedfunk** [comment]
Related problem:

I ran `:Copilot setup` and it worked

![image](https://user-images.githubusercontent.com/661038/161642434-012d70e7-bd26-465a-bc9c-04b21da67d9c.png)

But I have no $XDG_CONFIG_HOME/github-copilot/` directory:

![image](https://user-images.githubusercontent.com/661038/161642471-10b20158-69e3-4401-abd9-67142aaf386b.png)

**Comment by zbirenbaum** [comment]
Are you on windows? If so try the patch I just sent out a second ago.

**Comment by mikedfunk** [comment]
No, I'm on MacOS.

Looks like it's in `~/.config`, which is probably what `$XDG_CONFIG_HOME` is intended for.

**Comment by mikedfunk** [comment]
I exported `$XDG_CONFIG_HOME` and now it's timing out after 10 seconds :/ 

![image](https://user-images.githubusercontent.com/661038/161643241-85cd456b-c8aa-4bd5-b896-b6b92c783035.png)

**Comment by zbirenbaum** [comment]
> No, I'm on MacOS.
> 
> Looks like it's in `~/.config`, which is probably what `$XDG_CONFIG_HOME` is intended for.

I just pushed an update a second ago that should default to ~/.config if XDG_CONFIG_HOME is not defined and user isn't on windows. If thats not working let me know.

I'm not sure why the request isn't working. It seems the error is in here:
```
local function oauth_user(token)
   local response = request({
      url = "https://api.github.com/user",
      headers = {
         Authorization = "Bearer " .. token,
      },
   })
   return json_body(response)
end
```

But that works fine for me.

If the latest commit fixes pathing stuff on packersync, can you open a new issue for the timeout?

**Comment by annenpolka** [comment]
@zbirenbaum Sorry for replying from a closed issue, but I found some problems in `find_config_path()`.

`expand('$VARIABLE')` will return the literal `'$VARIABLE'` when the envvar is not defined.
`expand($VARIABLE)` works as you intended, but there seems no way to do this from Lua `vim.fn.expand()`.

`expand("~/AppData/Local")` won't check if path exists. It just returns `/home/username/AppData/Local` even in Linux.

**Comment by zbirenbaum** [comment]
> @zbirenbaum Sorry for replying from a closed issue, but I found some problems in `find_config_path()`.
> 
> 
> 
> `expand('$VARIABLE')` will return the literal `'$VARIABLE'` when the envvar is not defined.
> 
> `expand($VARIABLE)` works as you intended, but there seems no way to do this from Lua `vim.fn.expand()`.
> 
> 
> 
> `expand("~/AppData/Local")` won't check if path exists. It just returns `/home/username/AppData/Local` even in Linux.
> 
> 

Thanks for the info, I'll add a check to make sure that the dir exists.

I think I could run filereadable on the hosts file using that as the relative path, but I'd prefer to check if the dir actually exists so that it still works once I no longer rely on copilot.vim for the pre-authentication step.

**Comment by zbirenbaum** [comment]
@annenpolka I just pushed a fix using the info you provided. I did a bunch of isdirectory checks and I added a print statement to indicate when none of the above locations were directories, so hopefully it behaves a bit more predictably now. Thanks for the catch!
