### ISSUE TITLE
Not getting anything from copilot

### ISSUE THREAD

**Issue by Gako358** [zbirenbaum/copilot.lua#10]
Been using copilot for a while, and got no problem other than it would be nice to have a lua pluggin.
When I try to install yours i get nothing. I have the folder with two files in .config/github-copilot
Files are hosts and terms both json files

Before I install yours I made sure the folders where there, then I uninstalled copilot.
Reloaded vim added your pluggins, as described.

```{
    "zbirenbaum/copilot.lua",
     event = "InsertEnter",
     config = function ()
       vim.schedule(function()
         require("copilot")
       end)
   end,
   },

  -- Copilot autocomplete
  -- Install after zbirenbaum copilot and load after nvim-cmp
   {
     'zbirenbaum/copilot-cmp',
     branch = "cycling_completions",
     after = {"copilot.lua", "nvim-cmp"},
   },
```

in my cmp for nvim cmp, I have it almost identical as yours, also because I did steal some from your config :P 

```
local cmp = require 'cmp'
local luasnip = require 'luasnip'

require("luasnip/loaders/from_vscode").lazy_load()
cmp.setup({
  snippet = {
    expand = function(args)
      require("luasnip").lsp_expand(args.body)
    end,
  },
  style = {
    winhighlight = "NormalFloat:NormalFloat,FloatBorder:FloatBorder",
  },
  window = {
    completion = {
      border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
      scrollbar = "║",
      autocomplete = {
        require("cmp.types").cmp.TriggerEvent.InsertEnter,
        require("cmp.types").cmp.TriggerEvent.TextChanged,
      },
    },
    documentation = {
      border = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" },
      winhighlight = "NormalFloat:NormalFloat,FloatBorder:FloatBorder",
      scrollbar = "║",
    },
  },
  mapping = {
    ["<PageUp>"] = function()
      for _ = 1, 10 do
        cmp.mapping.select_prev_item()(nil)
      end
    end,
    ["<PageDown>"] = function()
      for _ = 1, 10 do
        cmp.mapping.select_next_item()(nil)
      end
    end,
    ["<C-p>"] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
    ["<C-n>"] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
    ["<C-d>"] = cmp.mapping.scroll_docs(-4),
    ["<C-f>"] = cmp.mapping.scroll_docs(4),
    ["<C-Space>"] = cmp.mapping.complete(),
    ["<C-e>"] = cmp.mapping.close(),
    ["<CR>"] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Replace,
      select = false,
    }),
    ["<Tab>"] = function(fallback)
      if cmp.visible() then
        cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback()
      end
    end,
    ["<S-Tab>"] = function(fallback)
      if cmp.visible() then
        cmp.select_prev_item({ behavior = cmp.SelectBehavior.Select })
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end,
  },
  experimental = {
    native_menu = false,
    ghost_text = true,
  },
  sources = {
    -- { name = "copilot", group_index = 2 },
    { name = "nvim_lsp", group_index = 2 },
    { name = "path", group_index = 2 },
    { name = "luasnip", group_index = 2 },
    { name = "buffer", group_index = 5 },
    { name = "nvim_lua", group_index = 2 },
  },
  sorting = {
    comparators = {
      cmp.config.compare.recently_used,
      cmp.config.compare.offset,
      cmp.config.compare.score,
      cmp.config.compare.sort_text,
      cmp.config.compare.length,
      cmp.config.compare.order,
    },
  },
  preselect = cmp.PreselectMode.Item,
})

--set max height of items
vim.cmd([[ set pumheight=6 ]])
--set highlights
local highlights = {
  CmpItemKindText = { fg = "LightGrey" },
  CmpItemKindFunction = { fg = "#C586C0" },
  CmpItemKindClass = { fg = "Orange" },
  CmpItemKindKeyword = { fg = "#f90c71" },
  CmpItemKindSnippet = { fg = "#565c64" },
  CmpItemKindConstructor = { fg = "#ae43f0" },
  CmpItemKindVariable = { fg = "#9CDCFE", bg = "NONE" },
  CmpItemKindInterface = { fg = "#f90c71", bg = "NONE" },
  CmpItemKindFolder = { fg = "#2986cc" },
  CmpItemKindReference = { fg = "#922b21" },
  CmpItemKindMethod = { fg = "#C586C0" },
  CmpItemMenu = { fg = "#C586C0", bg = "#C586C0" },
  CmpItemAbbr = { fg = "#565c64", bg = "NONE" },
  CmpItemAbbrMatch = { fg = "#569CD6", bg = "NONE" },
  CmpItemAbbrMatchFuzzy = { fg = "#569CD6", bg = "NONE" },
}
vim.api.nvim_set_hl(0, "CmpBorderedWindow_FloatBorder", { fg = "#565c64" })
for group, hl in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, hl)
end
```

If you need anyting more please let me know, 
my nvim config is at: https://github.com/Gako358/Dotfiles/tree/a20b50ea6c4bad1c8ddc4e36383947c97234f1c9/.config/nvim

I have commented out your plugins and back using copilot.vim, until a solution is at place.
Any help when you got time is much appreciated.

**Comment by zbirenbaum** [comment]
Are you on .6 or .7? Can you set up an autocmd to call `require('copilot.utils').send_completion_request()` on InsertChange and see if any results are printed?

**Comment by Gako358** [comment]
I am on version .6

Not really sure how I am to set up the call, if you could explain.

**Comment by Gako358** [comment]
Now when I tried again to use your plugin, 
```
packer.nvim: Error running config for copilot.lua ...site/pack/packer/start/copilot.lua/lua/copilot/setup.lua:45: Expected value but found invalid token at character 4
```

**Comment by zbirenbaum** [comment]
> Now when I tried again to use your plugin, 
> 
> ```
> 
> packer.nvim: Error running config for copilot.lua ...site/pack/packer/start/copilot.lua/lua/copilot/setup.lua:45: Expected value but found invalid token at character 4
> 
> ```

Ah this is due to a syntax type, presumably in whatever you wrote for the Autocmd.

Try this

vim.cmd("au InsertChange * lua require('copilot.utils').send_completion_request()")

**Comment by Gako358** [comment]
![copilot](https://user-images.githubusercontent.com/42249650/162032692-0505146f-3982-41d1-93d9-a71163d1a51e.png)

Here is the LspInfo, 
Will try the revert back to your plugin and give feedback in a sec

**Comment by zbirenbaum** [comment]
> ![copilot](https://user-images.githubusercontent.com/42249650/162032692-0505146f-3982-41d1-93d9-a71163d1a51e.png)
> 
> Here is the LspInfo, Will try the revert back to your plugin and give feedback in a sec

Yeah I need the :LspInfo output when copilot.lua is installed and set up. If you are having the issue where it isn’t attached then it would make sense. I’ll have a fix for that soon. If it’s a different issue I’d like to be aware of it

**Comment by zbirenbaum** [comment]
> ![copilot2](https://user-images.githubusercontent.com/42249650/162034766-0e70e1e9-0d5b-48f4-a40c-11729f5c9e9e.png)
> 
> 
> 
> This is when your plugin is loaded
> 
> 
> 
> Here is the LspInfo when your plugins are loaded
> 
> ![copilot3](https://user-images.githubusercontent.com/42249650/162034845-ec7e13a8-73c0-4b48-9ba0-77e9dc57edd5.png)
> 
> 
> 
> I used vim.cmd("au InsertChange * lua require('copilot.utils').send_completion_request()")
> 
> 
> 
> 

Even if it isn’t attached it should show that it starts. Did you update your config to require(“copilot”).setup() instead of just require(“copilot”)? I know in the original post it was just require("copilot") but your config on GitHub doesn't have copilot.lua in it so I can't really tell what's going on or if you updated that

**Comment by Gako358** [comment]
https://github.com/Gako358/Dotfiles/blob/f827e6a1098940e2c76f9266153c545984e59110/.config/nvim/lua/plugins/load.lua

It is commented out now, but as you can see I have .setup()

**Comment by zbirenbaum** [comment]
I just pushed an update. Can you try now and see what LspInfo says?

**Comment by Gako358** [comment]
![copilot4](https://user-images.githubusercontent.com/42249650/162042096-d6ad8005-8127-433a-9a41-be8e6bd40c14.png)

LspInfo is the same

**Comment by Gako358** [comment]
![copilot5](https://user-images.githubusercontent.com/42249650/162042651-9dbbc1d2-5255-4326-aed1-d54d18fe2729.png)

This is after I clear cache and try to run a PackerCompile

**Comment by kozer** [comment]
@Gako358 I noticed something, and I want to test my theory.
I, personaly, get suggestions only on the root level of the file.
If my cursor is inside a function, I get nothing. Is this the same for you as well?

**Comment by Gako358** [comment]
You mean from copilot? If so, i get no suggestions from copilot, everything else work.

**Comment by kozer** [comment]
Yeah, I mean from copilot. You are not getting anything at all? Did you try at the root level of the file?

**Comment by Gako358** [comment]
Yes, also getting error when running, if you see post before your first comment, hoping it will be sorted out

**Comment by zbirenbaum** [comment]
The issue with not getting completions inside functions has been addressed. You should now have completions in all contexts exactly as with copilot.vim. Please :PackerSync and let me know if this is not the case.
