### ISSUE TITLE
Can't `:Copilot auth` after loading a session

### ISSUE THREAD

**Issue by D00mch** [zbirenbaum/copilot.lua#100]
When I open Neovim and run the `:Copilot auth` command, I see the output `[Copilot] Authenticated as GitHub user: D00mch`. I can still see the same output if I open a file with `:e <path>` after loading the session.

However, if I load a session with [Neovim Session Manager](https://github.com/Shatur/neovim-session-manager) and run the same command, I see the output `[Copilot] Not running`.

**Comment by MunifTanjim** [comment]
Looks like Neovim lost track of the LSP server that Copilot starts. You should probably ask about this problem on [neovim-session-manager](https://github.com/Shatur/neovim-session-manager), since they'll have better idea why this might happen.

**Comment by D00mch** [comment]
One workaround I found is to have a keymap to setup Copilot after the session is loaded.

**Comment by D00mch** [comment]
The nvim-session-manager author proposed: 
> Hi! This could happen because we shutdown all LSP servers. You probably should ask copilot.lua to re-enable copilot after restarting LSP.

**Comment by snowair** [comment]
Yes, I agree that copilot.lua should give a function to restart the copilot LSP server.  Because switch between projects meas the whole workspace and program language changed. Any LSP server must restart.

**Comment by snowair** [comment]
@MunifTanjim #112 

```
    use {
        "zbirenbaum/copilot.lua",
        branch = "feat-smart-setup",
        cmd = "Copilot",
        after = "bufferline.nvim", 
        config = function()
            vim.defer_fn(function()
                require("copilot").setup()
            end, 100)
        end,
    }

```

Run: `Copilot auth`, get  `Client 5 quit with exit code 1 and signal 0`

**Comment by MunifTanjim** [comment]
You shouldn't need `vim.defer_fn`. Can you try removing that?

**Comment by snowair** [comment]
> You shouldn't need `vim.defer_fn`. Can you try removing that?

Yeah, I works now.

**Comment by snowair** [comment]
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/1695133/214260049-0e4862c1-e1a2-4763-bd54-a8feab8ed9d2.png">

I get anther error
