### ISSUE TITLE
RPC error,  code_name = unknown,  Not authenticatd Not signedin 

### ISSUE THREAD

**Issue by PorcoRosso85** [zbirenbaum/copilot.lua#101]
When trying openning panel, I've got error.
When I'm investigating why I can't work copilot.lua and its completion, I've found this.

![image](https://user-images.githubusercontent.com/40359643/210977741-6aac251e-333c-4f5a-b149-d913f9082553.png)
![image](https://user-images.githubusercontent.com/40359643/210974697-999eca6a-d3bf-4dfe-93ca-499e43f5336a.png)
![image](https://user-images.githubusercontent.com/40359643/210974881-9fa6835c-3ee1-4186-89b8-0f35b5fb57e2.png)
![image](https://user-images.githubusercontent.com/40359643/210975055-876f1570-7aa4-4d55-8d93-cb0bb11ac1bf.png)
![image](https://user-images.githubusercontent.com/40359643/210977226-b9390cb8-93c2-472d-a1d8-f88499395c9d.png)

Hi, is there who has got same error message as mine?

<details>
<summary>Copilot Configuration, Click here</summary>

```copilot.lua
require('copilot').setup({
  panel = {
    enabled = true,
    auto_refresh = false,
    keymap = {
      jump_prev = "[[",
      jump_next = "]]",
      accept = "<CR>",
      refresh = "gr",
      open = "<M-CR>"
    },
  },
  suggestion = {
    enabled = true,
    auto_trigger = false,
    debounce = 75,
    keymap = {
      accept = "<M-CR>",
      accept_word = false,
      accept_line = false,
      next = "<M-]>",
      prev = "<M-[>",
      dismiss = "<C-]>",
    },
  },
  filetypes = {
    yaml = true,
    markdown = true,
    help = false,
    gitcommit = false,
    gitrebase = false,
    hgcommit = false,
    svn = false,
    cvs = false,
    ["."] = false, -- e.g. .dots, .env
    terraform = true,
    -- ["*"] = false, -- disable for all other filetypes and ignore default `filetypes`
  },
  -- copilot_node_command = 'node', -- Node.js version must be > 16.x
  server_opts_overrides = {
    trace = "verbose",
    settings = {
      advanced = {
        listCount = 10, -- #completions for panel
        inlineSuggestCount = 3, -- #completions for getCompletions
      }
    },
  }
})

```
</details>

I've install copilot just only copilot lua.
No from node, no from copilot.vim.
I recognize that copilot.lua require us to install only itself.
If I'm wrong and error occurs why, please tell me anything.

Thanks.

P.S.1, what I've investigated
same error on neovim, I've found this page only on google.
does this page help us?
https://github.com/neovim/nvim-lspconfig/issues/1815

**Comment by MunifTanjim** [comment]
Can you try with Node.js 16 or 18?

**Comment by MunifTanjim** [comment]
> Node 16 is required.

Recent `copilot.vim` says it supports 16+: https://github.com/github/copilot.vim/blob/324ec9eb69e20971b58340d0096c3caac7bc2089/autoload/copilot/agent.vim#LL364

I've never tried with 19 tho.

---

Also found this: https://github.com/community/community/discussions/35862

Looks like `:Copilot auth signout` then `:Copilot auth signin` might fix it.

**Comment by zbirenbaum** [comment]
> > Node 16 is required.
> 
> 
> 
> Recent `copilot.vim` says it supports 16+: https://github.com/github/copilot.vim/blob/324ec9eb69e20971b58340d0096c3caac7bc2089/autoload/copilot/agent.vim#LL364
> 
> 
> 
> I've never tried with 19 tho.
> 
> 
> 
> ---
> 
> 
> 
> Also found this: https://github.com/community/community/discussions/35862
> 
> 
> 
> Looks like `:Copilot auth signout` then `:Copilot auth signin` might fix it.

Really?! Glad they finally added support, should cut down on issues dramatically

**Comment by PorcoRosso85** [comment]
@MunifTanjim 
@zbirenbaum 

Solved.
```
<Plug> Copilot auth signout
<Plug > Copilot auth signin
```
Thanks a lot.


By the way, is there the explanation of "Copilot auth [arguments]"?
I've tried to un-plug and re-plug copilot.lua on plug manager, but I did not signout from github.

If existed, will you let me know where the explanation of that?Excuse me.
Thanks.

**Comment by MunifTanjim** [comment]
The auth information is usually stored in `~/.config/github-copilot/hosts.json` file.

**Comment by PorcoRosso85** [comment]
> 通常、認証情報は`~/.config/github-copilot/hosts.json`ファイルに保存されます。

Thanks.
Checked.
