### ISSUE TITLE
Module 'copilot' not found on Require

### ISSUE THREAD

**Issue by oacs** [zbirenbaum/copilot.lua#104]
I did a fresh install for the plugin but when I tried to call the setup function for copilot it says that the module is not define.

![image](https://user-images.githubusercontent.com/13282482/212166567-5aa8a6a8-742a-4a5f-8118-6f5de61417ae.png)

I tried reinstalling packer and copilot.lua and failed to make it work, I'm a bit frustrated because I know that I'm missing something here

```
use {
  "zbirenbaum/copilot.lua",
  cmd = "Copilot",
  event = "VimEnter",
  config = function()
    vim.defer_fn(function()
      require("copilot").setup()
    end, 100)
  end,
}

use {
  "zbirenbaum/copilot-cmp",
  after = { "copilot.lua" },
  config = function ()
    require("copilot_cmp").setup()
  end
}
```

**Comment by zbirenbaum** [comment]
See what happens if you run `vim.cmd('packadd copilot')` before  `require('copilot').setup()`

If that doesn't work, try to debug while not lazy loading either plugin. Just remove the cmd and event fields, and take it out of the defer.

You can also try pasting in this snippet which I took directly from my own config:
```
  ["zbirenbaum/copilot.lua"] = {
    after = "nvim-lspconfig",
    config = function()
      vim.defer_fn(function()
        require("copilot").setup({
          suggestion = { enabled = false },
          panel = { enabled = false },
        })
      end, 100)
    end,
  },
  ["zbirenbaum/copilot-cmp"] = {
    after = { "copilot.lua", "nvim-cmp" },
    config = function ()
      require("copilot_cmp").setup({
        clear_after_cursor=true,
      })
    end
  },
```

**Comment by oacs** [comment]
Thank you for the help, the issue fix it self over night, I think my packer might had some issues running the config function at the wrong time( talking no sense here), I can close this one.

PD: copilot cmp work like a charm after the issue with copilot require solved itself

**Comment by hobo1618** [comment]
Hello hello, 

I got the same error after running PackerSync earlier. I was able to fix the error by removing these lines:

```lua
  cmd = "Copilot",
  event = "VimEnter",
```
Copilot and copilot-cmp appear to working now, but does this mean the packages aren't lazy loaded anymore?

Also, if it's useful info, the copilot package was initially saved to the `share/nvim/site/pack.packer/opt/` directory, which doesn't appear in the list of directories in the error message above. I was also able to "fix" the error by moving the copilot.lua package from `/opt/copilot.lua` to `/start/copilot.lua`. After PackerSync, though, the package at `/start/copilot.lua` is removed, so not a viable solution. Is there some sort of PATH type variable that I need to update?

in `packer_compiled` here's what I have after commenting out the aforementioned lines:

```lua
  ["copilot-cmp"] = {
    config = { "\27LJ\2\n9\0\0\3\0\3\0\0066\0\0\0'\2\1\0B\0\2\0029\0\2\0B\0\1\1K\0\1\0\nsetup\16copilot_cmp\frequire\0" },
    load_after = {},
    loaded = true,
    needs_bufread = false,
    path = "/home/hobo/.local/share/nvim/site/pack/packer/opt/copilot-cmp",
    url = "https://github.com/zbirenbaum/copilot-cmp"
  },
  ["copilot.lua"] = {
    after = { "copilot-cmp" },
    config = { "\27LJ\2\n]\0\0\3\0\6\0\n6\0\0\0009\0\1\0'\2\2\0B\0\2\0016\0\3\0'\2\4\0B\0\2\0029\0\5\0B\0\1\1K\0\1\0\nsetup\fcopilot\frequire\20packadd copilot\bcmd\bvim-\1\0\4\0\3\0\0066\0\0\0009\0\1\0003\2\2\0)\3d\0B\0\3\1K\0\1\0\0\rdefer_fn\bvim\0" },
    loaded = true,
    only_config = true,
    path = "/home/hobo/.local/share/nvim/site/pack/packer/start/copilot.lua",
    url = "https://github.com/zbirenbaum/copilot.lua"
  },
```
It looks suspiciously similar to the snippets you provided, but I couldn't figure out where I was supposed to paste them. Do they go in packer.lua with all the other use {} imports? Somewhere else? 

Thanks so much. Let me know if I can provide more details.
