### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by nikarc** [zbirenbaum/copilot.lua#105]
Hey! I'm really struggling to get this plugin working, I'm hoping someone can help me figure this out.

I had originally installed tpope's `copilot.nvim` and authenticated through that plugin, and had it working showing suggestions.

I'm now trying to use this plugin instead, with the hopes of eventually pairing it with `copilot-cmp`, but I'm not getting any inline suggestions at all.

Here's how I'm setting up the plugin:
```lua
  -- Copilot
  use {
    "zbirenbaum/copilot.lua",
    cmd = "Copilot",
    event = "VimEnter",
    config = function()
      vim.defer_fn(function()
        require("copilot").setup({
          copilot_node_command = vim.fn.expand("$HOME")..'/n/bin/node',
        })
      end, 100)
    end,
  }
```

Here's `:Copilot status`:

![image](https://user-images.githubusercontent.com/3580396/212218609-a6dfa2b1-de43-4c65-b69a-336111ce0103.png)

Here's my `:LspInfo` output, where I noticed `filetypes` is empty:

![image](https://user-images.githubusercontent.com/3580396/212218013-763856bd-74dd-44fe-8b81-c36ce6010623.png)

I _am_ however able to get suggestions via `:Copilot panel`:

![image](https://user-images.githubusercontent.com/3580396/212218989-69fd794f-887e-4cf3-b8f5-c31315e8cf1b.png)

I'm currently on MacOS, but i've also tried Arch Linux without any luck.

**Comment by zbirenbaum** [comment]
What happens if you run `:Copilot suggestion`? If that fixes it, you may want to try explicitly enabling suggestions in your config.

Also, are you using copilot-cmp? Right now copilot-cmp and inline suggestions are mutually exclusive.

**Comment by nikarc** [comment]
`:Copilot suggestion` does nothing, no output.

I don't currently have `copilot-cmp` installed. I installed it briefly earlier, but it didn't work. Then i noticed i can't even get the inline suggestions to work so i figured i should get that working first?

**Comment by nikarc** [comment]
Ok that did @MunifTanjim , thanks :+1: . I didn't realize it needed to be explicitly set to `auto_trigger`
