### ISSUE TITLE
Disable copilot for `.env` files

### ISSUE THREAD

**Issue by primeapple** [zbirenbaum/copilot.lua#111]
In `.env` files, Neovim is giving me the filetype `sh`, the same as in `.sh` files.
This means I can't disable Copilot for `.env` files without disabling it also for `.sh` files?

Would it be possible to disable Copilot for `.env` files, but keep it on for `.sh` files?

**Comment by MunifTanjim** [comment]
@primeapple can you try out https://github.com/zbirenbaum/copilot.lua/issues/113 and see if that solves the issue?
