### ISSUE TITLE
Copilot sometimes only gets the first line of the suggestion (python)

### ISSUE THREAD

**Issue by bellini666** [zbirenbaum/copilot.lua#114]
Some strange behaviour here:

This is a simple example of it givving a suggesting in an empty python file:
![image](https://user-images.githubusercontent.com/134025/215346239-024e4251-8591-4e3b-81ef-e7de381593dc.png)

This is the same suggestion in a project of mine:
![image](https://user-images.githubusercontent.com/134025/215346263-7c605b88-58c2-445f-83c1-8cca043465c8.png)

And this is the same suggestion in another project:
![image](https://user-images.githubusercontent.com/134025/215346277-c96854a5-d846-4a6d-9209-16f0ccd3b2ab.png)

I'm using https://github.com/zbirenbaum/copilot-cmp, but added my own formatting functions to check what was going on, and they really came like that from copilot.lua

obs. I used fibonacci as a "foobar example", but it happens with everything inside that project

**Comment by bellini666** [comment]
obs. I tried using both `getCompletionsCycling` and `getPanelCompletions`, both produced the same issue

**Comment by MunifTanjim** [comment]
> I tried using both getCompletionsCycling and getPanelCompletions, both produced the same issue

afaik, that config is broken in `copilot-cmp`.

---

And about the suggestion, my guess is that Copilot is suggesting one line in those places for some reason. What suggestion you get is completely dependent on Copilot. These plugins are just provide the UI to display the suggestion Copilot generates.

**Comment by bellini666** [comment]
> And about the suggestion, my guess is that Copilot is suggesting one line in those places for some reason. What suggestion you get is completely dependent on Copilot. These plugins are just providing the UI to display the suggestion Copilot generates.

Oh, I see. Do you know where should I report this issue for copilot?

Also, is there a way for me to ensure that I'm really using the latest copilot version available? Haven't check the code yet to understand how it retrieves the copilot upstream code

**Comment by MunifTanjim** [comment]
> Do you know where should I report this issue for copilot?

They take feedbacks here: https://github.com/community/community/discussions/categories/copilot

> Also, is there a way for me to ensure that I'm really using the latest copilot version available? Haven't check the code yet to understand how it retrieves the copilot upstream code

`:Copilot version` should give you the info.

**Comment by bellini666** [comment]
@MunifTanjim thanks! Just found a related issue there: https://github.com/community/community/discussions/40522

**Comment by zbirenbaum** [comment]
> > I tried using both getCompletionsCycling and getPanelCompletions, both produced the same issue
> 
> 
> 
> afaik, that config is broken in `copilot-cmp`.

getPanelCompletions at the time of implementing that handler was much much faster than it is now. While I did put a disclaimer about that in the Readme, realistically just removing it is probably the best call at this point.

**Comment by MunifTanjim** [comment]
https://github.com/orgs/community/discussions/40522#discussioncomment-4701470
