### ISSUE TITLE
Force encoding type to not conflict with other servers

### ISSUE THREAD

**Issue by AniAggarwal** [zbirenbaum/copilot.lua#118]
It seems copilot.lua acts as an lsp server, but I am not able to find the option to change its offsetEncoding as I would be able to with other LSPs. 
This would be a great feature because, currently, copilot uses a different offsetEncoding than clangd, and I am unable to force both clangd, null-ls, and copilot to use the same offset encoding. This results in annoying warning messages and possibly other issues.

**Comment by MunifTanjim** [comment]
[Copilot's LSP Server](https://github.com/github/copilot.vim/tree/release/copilot/dist) only supports UTF-16. You can't change that. It won't work otherwise.

**Comment by MunifTanjim** [comment]
You might be interested in this comment: https://github.com/neovim/nvim-lspconfig/issues/2184#issuecomment-1273705335
