### ISSUE TITLE
can't get automatic suggestions

### ISSUE THREAD

**Issue by danielo515** [zbirenbaum/copilot.lua#123]
Hello.
I read the #105 issue, and I am facing almost the same exact issues as the original poster, with the difference that I activated auto_trigger since the very beginning.
I am able to trigger the suggestions with the keymap, but not very reliably.
The way I expect this to work, is to get a suggestion as soon as it is available, but right now it seems to require me to type something before.
For example, and taking the examaple from #105, if I type

```lua
-- Fibonnaci

```
And I position the cursor in the second line, I get nothing. I can force it with my next keymap, but the suggestion is not great. However, if I type `local` then force it with the keymap, I then get what I expect:
![image](https://user-images.githubusercontent.com/2270425/218998296-f361dee1-51db-4418-a052-0232f6009a59.png)

That is what I would want to see as soon as copilot has suggestions available. How can I debug or force this?

This is my config:

```lua
{
  "zbirenbaum/copilot.lua",
  cmd = "Copilot",
  event = "InsertEnter",
  config = function()
    require("copilot").setup {
      panel = {
        enabled = true,
        auto_refresh = true,
        keymap = {
          jump_prev = "[[",
          jump_next = "]]",
          accept = "<CR>",
          refresh = "gr",
          open = "<M-CR>",
        },
        layout = {
          position = "bottom", -- | top | left | right
          ratio = 0.4,
        },
      },
      suggestion = {
        enabled = true,
        auto_trigger = true,
        debounce = 75,
        keymap = {
          accept = "<S-Tab>",
          accept_word = false,
          accept_line = false,
          next = "<M-b>",
          prev = "<M-v>",
          dismiss = "<C-e>",
        },
      },
      filetypes = {
        yaml = false,
        markdown = false,
        help = false,
        gitcommit = false,
        gitrebase = false,
        hgcommit = false,
        svn = false,
        cvs = false,
        ["."] = false,
      },
      copilot_node_command = "node", -- Node.js version must be > 16.x
      server_opts_overrides = {},
    }
  end,
}
```

**Comment by MunifTanjim** [comment]
What suggestion copilot generates can't be controlled by this plugin. This plugin just displays the suggestions when copilot gives it to us.

Here's my experience.

- With `-- Fibonnaci`, I didn't get any suggestion immediately after entering the new line. I got the suggestion when I typed `l`.
- With a more explicit prompt `-- write a function to calculate fibonacci numbers`, I got suggestion as soon as entering new line without typing anything else.

![Kapture 2023-02-15 at 20 53 54](https://user-images.githubusercontent.com/8050659/219062826-7e2bfb4a-5d37-4761-9c12-6c52be323e8c.gif)

> That is what I would want to see as soon as copilot has suggestions available. How can I debug or force this?

You can complain or give feedback about copilot here:  https://github.com/community/community/discussions/categories/copilot

**Comment by danielo515** [comment]
Thanks for your answer @MunifTanjim.
I tried your prompt, and I get the same behavior: nothing happens until I hit my next suggestion keymap, which then appears quite fast. To me it is clear that the problem is that it is not triggering, that's why I would like to have some debug points or something where I can see what it is happening under the hood.

**Comment by MunifTanjim** [comment]
You can do this to see if status is changing:

```lua
require('copilot.api').register_status_notification_handler(function(data)
  print("Copilot Status: " .. data.status)
end)
```

When copilot is generating suggestions, it should print "InProgress".

Other than that, you can add print statement here to check if this code-path is triggering when you're typing: https://github.com/zbirenbaum/copilot.lua/blob/f1b330351d755e905cffe1dea2f6e0a6f273c9fe/lua/copilot/suggestion.lua#L250-L259

**Comment by danielo515** [comment]
Oh, I did that just after posting my previous message, but thanks for the help. This is my diff:
![image](https://user-images.githubusercontent.com/2270425/219295359-c1392764-b718-41b2-b5bf-aa94ab3619d3.png)

That was enough to get a gist of what was going on, and then something very weird started happening: it now works as expected. Why? Who knows. Maybe because I was forced to run packer-compile to make my changes work, or maybe because the print statements force vim to process it in the main thread? I don't know. I will remove the print statements and see if it still works.

**Comment by danielo515** [comment]
Yep, I can confirm that it still works after removing the print statements. It seems that the problem fix was one packer compile away. The reasoning behind this though is way beyond my understanding. If commands were registered, key-maps were registered, why the hell an extra packer compile was needed?

In any case, thanks for your patience and help, and of course this great plugin. I'll leave the pleaaure of closing the issue to you.
