### ISSUE TITLE
"Contact Support" error

### ISSUE THREAD

**Issue by rudenkornk** [zbirenbaum/copilot.lua#125]
Hi,

Thanks for this awesome plugin! I've been using it for the last 6 months or so and it never failed.
But for the recent couple of days I am facing an issue where copilot suggest me to "Contact Support" on `Copilot Auth` or `Copilot Status` commands. Sometimes adding that I am not authorized. 
The problem is that I am authorized (or at least did my best):
1. I have an active GitHub Copilot subscription
2. I deleted `~/.config/github-copilot/hosts.json` credentials file, removed previous auth from github settings and re-logged in using `:Copilot Auth`. After authorization this command responds with "Contact Support" error.

```bash
> :Copilot Status

Contact Support

Request Actions:
1. Contact Support
3. Dismiss
Type number and <Enter> or click with the mouse (q or empty cancels): [Copilot] Online
[Copilot] Not authorized
```

**Comment by MunifTanjim** [comment]
Try `:Copilot auth signout` then `:Copilot auth signin`

**Comment by MunifTanjim** [comment]
Also update to latest version.

**Comment by rudenkornk** [comment]
I am using the latest version `f1b330351d755e905cffe1dea2f6e0a6f273c9fe` from Feb 16. Signout-signin did not help unfortunatelly.
![image](https://user-images.githubusercontent.com/28059451/219316655-09ebfc0f-8367-4808-a170-1f5e9ccf92df.png)

**Comment by MunifTanjim** [comment]
What happens if you type `1` and then press `Enter`? 😂 Not sure where it's coming from...

**Comment by MunifTanjim** [comment]
Not sure why this is happening for you.

Can you add a log before this line: https://github.com/zbirenbaum/copilot.lua/blob/f1b330351d755e905cffe1dea2f6e0a6f273c9fe/lua/copilot/client.lua#L128

```lua
print(vim.inspect(set_editor_info_params))
```

And paste the output here?

**Comment by rudenkornk** [comment]
Sure. I did not find where `print` output goes, so I inserted and error instead. Here is the result:

```lua
{
  editorConfiguration = {
    disabledLanguages = { {
        languageId = "."
      }, {
        languageId = "cvs"
      }, {
        languageId = "gitcommit"
      }, {
        languageId = "gitrebase"
      }, {
        languageId = "help"
      }, {
        languageId = "hgcommit"
      }, {
        languageId = "markdown"
      }, {
        languageId = "svn"
      }, {
        languageId = "yaml"
      } },
    enableAutoCompletions = false
  },
  editorInfo = {
    name = "Neovim",
    version = "0.8.3 + Node.js 18.12.1"
  },
  editorPluginInfo = {
    name = "copilot.vim",
    version = "1.8.3"
  }
}
```

**Comment by MunifTanjim** [comment]
Everything looks good there. I also tried with nodejs `18`... working for me.

Not sure what's going on 😅

The only other thing you can try now is to check if `github/copilot.vim` plugin works for you.

**Comment by rudenkornk** [comment]
Hm.. the error repeats with the official plugin too. Even more, it repeats on the completely clean system (freshly started `podman` container with `ubuntu:22.10`) and minimal setup (`neovim`, `git`, `nodejs` apt packages).
Probably something is wrong with my network configuration.

**Comment by CursedWizard** [comment]
Looks like Microsoft started limiting usage from Russian IPs again. Try using non-Russian proxy

**Comment by rudenkornk** [comment]
Thanks, that worked. 😔
