### ISSUE TITLE
the content/font of the suggestion is always shaking

### ISSUE THREAD

**Issue by uxfion** [zbirenbaum/copilot.lua#130]
# When I do the typing, the content/font of the Suggestion prompt is always **jittering**.

## I'm not quite sure if this jittering is inherently present or caused by a bug.

The video below is using `copilot.lua` and the font has a noticeable jitter

https://user-images.githubusercontent.com/44778029/220706299-52bcc396-cbd8-4aab-8e40-86632f17f4e4.mov

And the video below is using `copilot.vim`, the font doesn't **shake** either when deleting or typing

https://user-images.githubusercontent.com/44778029/220706438-978cd1f5-2c2e-4670-b49b-b1a087959fe1.mov

I have no clue to solve this problem. Please let me know if there is any progress on this

**Comment by MunifTanjim** [comment]
@uxfion can you check https://github.com/zbirenbaum/copilot.lua/pull/131?

**Comment by uxfion** [comment]
> @uxfion can you check #131?


I used the new branch `fix-suggestion-flicker`

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/44778029/220935725-5f52baca-30b0-4c1d-99d2-39854955471c.png">

and it showed an error at line 190 of `sugestion.lua`

**Comment by MunifTanjim** [comment]
Pushed a fix... how about now? 🤔

**Comment by uxfion** [comment]
https://github.com/zbirenbaum/copilot.lua/pull/131#issuecomment-1441963620
