### ISSUE TITLE
Segfaults after attempted completion

### ISSUE THREAD

**Issue by textzenith** [zbirenbaum/copilot.lua#134]
Hi,

Thanks for having the vision to create this amazing plugin. Modern-day AIs are a wondrous technology, but can create nothing on their own. We need visionary people to build the human / AI interfaces that will make this technology into a tool that improves our daily lives.

A couple of times so far, I've been using this plugin and my Neovim has immediately segfaulted after a completion.

I can't say that any specific behaviour has caused these crashes—once I've noticed a pattern, I'll let you know. I've been using Copilot.lua for a few days without any problems. And then, suddenly, I've had two crashes in one day.

I haven't got Neovim set up for debugging, so I'm making this issue pre-emptively. I shall follow the guide at `debug.txt`—but this will be a bit of an adventure, so bear with me!

I have over 200 plugins, so I can't say it isn't some strange interaction of them that is causing this.

While I get the debug info ready, perhaps someone else can chime in with their ideas why this might be happening?

Thanks for your patience!

**Comment by textzenith** [comment]
Haven't update my Neovim in a while, so I'll make a quick update of everything and see of the crashes continue.

**Comment by MunifTanjim** [comment]
> Thanks for having the vision to create this amazing plugin. Modern-day AIs are a wondrous technology, but can create nothing on their own. We need visionary people to build the human / AI interfaces that will make this technology into a tool that improves our daily lives.

That should go in there: https://github.com/community/community/discussions/categories/copilot

---

> While I get the debug info ready, perhaps someone else can chime in with their ideas why this might be happening?

What's the output of `:Copilot version`?

**Comment by MunifTanjim** [comment]
Let's reopen if it's actually related to this plugin.
