### ISSUE TITLE
Halt on the `auth` panel

### ISSUE THREAD

**Issue by meijieru** [zbirenbaum/copilot.lua#138]
After I authorized through the brower, I stuck on the panel.
![image](https://user-images.githubusercontent.com/9511136/225204535-f162433a-ae2e-45f1-8141-2387b1f8d301.png)

Does it make a difference if I authorize WSL2 using a Windows browser?
Additionally, where can I locate the Copilot log to gain more insight into the issue?

**Comment by MunifTanjim** [comment]
How long was it stuck? Sometimes it takes a few minutes.

**Comment by meijieru** [comment]
Forever lol.

**Comment by MunifTanjim** [comment]
Unfortunately there are no additional logs that you can check. You can try adding some `print` statements here: https://github.com/zbirenbaum/copilot.lua/blob/b41d4c9c7d4f5e0272bcf94061b88e244904c56f/lua/copilot/auth.lua#L58-L98
to figure out exactly where it's getting stuck. Most probably https://github.com/zbirenbaum/copilot.lua/blob/b41d4c9c7d4f5e0272bcf94061b88e244904c56f/lua/copilot/auth.lua#L84
is never returning result. If that's the case, it might be some issue with your account or network.

---

Another thing you can try is install the official plugin [`copilot.vim`](https://github.com/github/copilot.vim) and try to sign in. If you sign in from that plugin then remove it and install `copilot.lua`, you'll still be signed into your account.

**Comment by meijieru** [comment]
[copilot.vim](https://github.com/github/copilot.vim) has the same problem.
