### ISSUE TITLE
Current Goals

### ISSUE THREAD

**Issue by zbirenbaum** [zbirenbaum/copilot.lua#14]
Now that I believe I have the copilot plugins in a stable state, here are the goals I have planned for the future:

- [x] Customization of result frequency: Currently, completions are requested by cmp which is debounced. I would like to add an option for _constant_ requests for results via the uv loop api, similar to how copilot.vim gets their completions. Depending on the frequency you set, you may have dramatic increases in CPU usage and editor latency, but I do think this is worth implementing.
- [x] Extend the api, make it easier to use: This one is pretty self explanatory, hooking into copilot and adding your own functionality and handlers should be made much simpler. By virtue of how cmp works, it was easier to just make the buf requests there to get a functional product, but this will need to be implemented as part of goal (1). Development of this will likely precede or occur alongside goal (1)
- [x] Fix copilot adding extraneous braces, brackets, parenthesis, etc: If characters like closing braces or parenthesis exist, copilot will insert additional ones, which kinda sucks. This isn't going to be easy and is an issue in copilot.vim as well, but if it's done well, it would be a major step forward.
- [x] Creation of hosts/terms json files should be implemented as copilot.vim does

???: Provide your input! What else would you like to see? Please feel free to comment and discuss here, or create an issue with the enhancement/feature flags.

**Comment by sbulav** [comment]
Hi Zack,
Thanks for your work on that plugin.
I would like to see the following things:

- Async startup of copilot(is it possible?)
- Specifying on which filetypes to start the plugin
- Configurable line length

Something like https://github.com/tzachar/cmp-tabnine#setup would be nice

**Comment by zbirenbaum** [comment]
Hi @sbulav, thank you for the input, just a couple of comments:

> * Async startup of copilot(is it possible?)

I'm not certain of what you mean by this. The server itself is a rpc, so neovim just sends out the command to start it. If you want to have it start automatically rather than InsertEnter, and still not affect startup time, using `vim.defer_fn` in your packer `use` to wrap the config should work.  It may just take some time playing with the value to get the correct behavior. See the README.md for more details on this.

> * Specifying on which filetypes to start the plugin

This is a great idea and something that should be released soon.

> * Configurable line length

I'm not sure what you mean by this. If here, you mean ask for completions of a certain length, that's not supported by copilot to my knowledge. The copilot discussion forum has also been complaining over the last couple days about general copilot performance regarding its ability to generate full functions/only getting one line, so it's not just the plugins I wrote...

We are somewhat at the mercy of copilot's api here. I did some testing for https://github.com/zbirenbaum/copilot-cmp/issues/5 and it turns out that while I can force a request for completions in such cases, the server returns no results.

I have requested an openai codex key, and whenever I get off that waitlist, I'll use it to make my own minimal lsp for completions.

**Comment by zbirenbaum** [comment]
@sbulav 

Checks have been written in to make sure copilot doesn't start in buffers like `help` or `packer`. ft_disable has been added to the params, so any languages you don't want to use copilot for can be input there. I think a blacklist makes more sense than a whitelist given the nature of copilot.

**Comment by sbulav** [comment]
Hi @zbirenbaum 
Thanks for your in-depth explanation!
I had significant input lag with `vim.schedule` on one of the previous `copilot.lua` versions, but with the latest version, the lag is gone.

As for the line length, I mean that sometimes completion, provided by the copilot, gets ridiculously long. Check out this example:
<img width="1592" alt="Screenshot 2022-04-13 at 10 24 18" src="https://user-images.githubusercontent.com/28604639/163124145-a4066bd2-ad1e-4da8-8b5b-00b6f9c30045.png">

I'd like to have an option to limit line length to, let's say, 80 symbols.

**Comment by zbirenbaum** [comment]
> Hi @zbirenbaum Thanks for your in-depth explanation! I had significant input lag with `vim.schedule` on one of the previous `copilot.lua` versions, but with the latest version, the lag is gone.
> 
> As for the line length, I mean that sometimes completion, provided by the copilot, gets ridiculously long. Check out this example: <img alt="Screenshot 2022-04-13 at 10 24 18" width="1592" src="https://user-images.githubusercontent.com/28604639/163124145-a4066bd2-ad1e-4da8-8b5b-00b6f9c30045.png">
> 
> I'd like to have an option to limit line length to, let's say, 80 symbols.

Glad to hear the lag issue is fixed!

I noticed that too, but I have cmp's max len limited so it never got that bad lol. I pushed an update to copilot-cmp just now, which caps it at 30 chars or abbreviates it with the first 20 + '...' + last 10 for the label. 

I'd like the user to be able to customize it, but integrating setup options has been an ongoing debate with myself regarding how to design them best. For now, I hope the change helps.

**Comment by zbirenbaum** [comment]
Quick update on this. The other day I actually managed to get copilot to get a completion on a newline, but cmp refused to show it, stating something along the lines of 'no prior character to complete' even when I try to manually trigger the menu. I think that this functionality is just incompatible with the way cmp is written. Unfortunately this is just an upstream problem I don't really have control over.

I am debating attempting to make a somewhat sizable PR to cmp which would fix this, but due to the scope of what is involved it would likely sit in the development branch for ages if it gets merged at all. I'll try digging into it at some point and see if there isn't an easier way, but I really wouldn't get your hopes up.

I am working on a few mechanical things that would make this type of feature work more smoothly which will be part of a rather sizable update coming soon:tm: but I think that for the time being getting this to integrate with cmp like the other results do is simply unrealistic. I'll continue to leave this open so that I can address it with the solution once said update is out, and I will probably put it in the docs as well.

As for the example implementations, I am happy to take input. Currently I was thinking that I would create a preview window triggerable by some command with selections and code previews.

**Comment by dklymenk** [comment]
Thank you for great work you did with the plugins.

Here are a couple of things that would be good to have:
* Some way to tell if there is an ongoing request to copilot servers. Being able to distinguish between "loading" state and "0 results" state would be a huge productivity boost for anyone using this plugin.
* An alternative to original plugin's `Copilot status`. I have been using the tpope's version for a few month before I switched to yours and I really miss the ability to check the status of the server after not getting any suggestions for a few minutes.

**Comment by MunifTanjim** [comment]
@dklymenk `:Copilot status` should now work as expected.
