### ISSUE TITLE
Request signInInitiate failed with message: Unexpected end of JSON input

### ISSUE THREAD

**Issue by DriedYellowPeach** [zbirenbaum/copilot.lua#140]
I have been used this plugin for quite a while. But today I tried to install it on one of my old laptop, when I `Copilot auth`, this error occurs: `Request signInInitiate failed with message: Unexpected end of JSON input`. I though it was network problem at first, but can't solve this unexpected end of json input after using proxy. So I had to switch to official `copilot.vim`, it turned out that `Copilot: 'Node.js version 16.x or newer required but found 14.0.0`. It would be better if `copilot.lua` told me directly that my node package is outdated.

**Comment by MunifTanjim** [comment]
The latest commit https://github.com/zbirenbaum/copilot.lua/commit/db62371b6eac73954c194f3c8faee36cffee8135 should notify you about unsupported node version.
