### ISSUE TITLE
copilot not producing panel completions

### ISSUE THREAD

**Issue by lennart7** [zbirenbaum/copilot.lua#148]
I am having trouble generating consistent panel predictions from copilot. The "trace" logs in LSP completion seem to indicate this is an error from the api.

```
[TRACE][2023-04-11 11:04:28] .../lua/vim/lsp.lua:1053   "notification"  "LogMessage"    {  extra = { "Producing empty solutions due to document version mismatch. Panel completions requested for document version 791 but document version was 790." },  level = 0,  message = "[DEBUG] [getPanelCompletions] [2023-04-11T09:04:28.086Z] Producing empty solutions due to document version mismatch. Panel completions requested for document version 791 but document version was 790.",  metadataStr = "[DEBUG] [getPanelCompletions] [2023-04-11T09:04:28.086Z]"}
```

So apparently the document changes somehow in between calls, preventing panel completions. I've noticed that the panel calls get created successfully when I predict with my cursor at the end of the document.

Would anyone know the reason for this? I've tested it on both LTS and Dev nvim. I am using LunarVim.
```
mason.nvim report
- OK neovim version >= 0.7.0
- OK **npm**: `8.1.2`
- OK **node**: `v16.13.2`
- OK **python3**: `Python 3.9.10`
- OK **pip3**: `pip 23.0.1 from ... (python 3.9)`
- OK **wget**: `GNU Wget 1.20.3 built on linux-gnu.`
- OK **curl**: `curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3`
- OK **gzip**: `gzip 1.10`
- OK **tar**: `tar (GNU tar) 1.30`
- OK **bash**: `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`
- OK **sh**: `Ok`
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Tue 11 Apr 2023 12:19:07 PM CEST.
```

**Comment by MunifTanjim** [comment]
How did you configure the plugin?

What's the output of `:Copilot version`?

**Comment by lennart7** [comment]
Hi there, thanks for the quick response.

I configured the plugins as follows, as recommended for packer / lvim:
```
    {
    "zbirenbaum/copilot.lua",
    event = { "VimEnter" },
    config = function()
      vim.defer_fn(function()
        require("copilot").setup {
          plugin_manager_path = os.getenv "LUNARVIM_RUNTIME_DIR" .. "/site/pack/packer",
        }
      end, 100)
    end,
    },
    {
      "zbirenbaum/copilot-cmp",
      after = { "copilot.lua" },
      config = function()
        require("copilot_cmp").setup()
      end,
    },
```

The output of `:Copilot version` is:
```
Neovim 0.9.0
copilot.vim 1.8.3
copilot.lua e6e6433537bc42d9150bcad931d6fbd4aea3f751
copilot/dist/agent.js 1.73.0
Node.js 16.13.2
```

**Comment by MunifTanjim** [comment]
Can you try getting rid of the `vim.defer_fn` and see if the situation improves?

**Comment by dancek** [comment]
I have this issue too. Version info and packer config snippet below (or [the full config](https://github.com/dancek/dotfiles/blob/17df2aa673591a9a33b9646f53b3120f2b124c2f/.config/nvim/lua/plugins.lua)).

```
Neovim 0.9.0                                                                
copilot.vim 1.8.3                                                           
copilot.lua decc8d43bcd73a288fa689690c20faf0485da217                        
copilot/dist/agent.js 1.73.0                                                
Node.js 19.9.0
```
```
  use {
    "zbirenbaum/copilot.lua",
    config = function ()
      require("copilot").setup()
    end
  }
  use {
    "zbirenbaum/copilot-cmp",
    after = { "copilot.lua" },
    config = function ()
      require("copilot_cmp").setup()
    end
  }
```

**Comment by MunifTanjim** [comment]
You might have some plugin that's changing the buffer after you open the copilot panel.

@dancek can you try disabling `Pocco81/auto-save.nvim` plugin and see if the issue still remains?

You can also try enabling panel `auto_refresh`, so that the panel automatically refreshes if buffer changes:

```lua
require("copilot").setup({
  -- other options
  panel = {
    -- other options
    auto_refresh = true,
  },
})
```

**Comment by MunifTanjim** [comment]
Let's reopen if this still exists.

**Comment by MunifTanjim** [comment]
It might just be a network issue. Copilot server might have blocked your IP for some reason, or you network might have some firewall. You can also try signout and signin again... that sometimes solves the issue.

**Comment by bastianlb** [comment]
I'd like to propose to open this again as after some time away from vim I'm still unable to get panel completions to work. Completions via cmp work fine. However, I also don't get any error messages in logs that requests from copilot are failing, just a silent "Synthesizing ?/0 solutions (Duplicates hidden) [loading]" at which point the panel seems stuck. 

Right now I'm using an out-of-the-box lazyvim config with all plugins and vim up to date.. Is anyone able to reproduce this? Would adding some error messages regarding failed copilot API requests be helpful here?

**Comment by MunifTanjim** [comment]
> copilot/dist/agent.js not running

Here the copilot server is not running at all.

**Comment by bastianlb** [comment]
Hey, thanks for the quick responses. I'm not sure why it wasn't running in this moment. I can generally reliably get cmp completions, just not panel completions.

![image](https://github.com/zbirenbaum/copilot.lua/assets/8620425/3b1cb704-edb2-4a2c-92be-c3ca8d384b4c)
