### ISSUE TITLE
nil value on 'plugin_path'

### ISSUE THREAD

**Issue by opxop** [zbirenbaum/copilot.lua#15]
im using LunarVim + nvim head branch, and get this message error at startup

```
Error executing vim.schedule lua callback: ...im/site/pack/packer/opt/copilot.lua/lua/copilot/util.lua:56: attempt to concatenate local 'plugin_path' (a nil value)
stack traceback:
        ...im/site/pack/packer/opt/copilot.lua/lua/copilot/util.lua:56: in function 'get_copilot_path'
        ...k/packer/opt/copilot.lua/lua/copilot/copilot_handler.lua:9: in function 'start'
        [string "..."]: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

so i replace my config following [this solution](https://github.com/zbirenbaum/copilot.lua/issues/3#issue-1192414954) because LunarVim things 😆, but still getting the same error message 

```diff
  {
    "zbirenbaum/copilot.lua",
    event = "InsertEnter",
    config = function()
      vim.schedule(function
-        require("copilot").setup()
+       require("copilot.copilot_handler").start(vim.fn.expand "$HOME" .. "/.local/share/lunarvim/")
      end)
    end,
  },

```

**Comment by opxop** [comment]
the output of nvim -v

```
NVIM v0.7.0-dev+1416-g012c05580
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by opxop@local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

```

**Comment by zbirenbaum** [comment]
Try this:

```
use {
    "zbirenbaum/copilot.lua",
    event = "InsertEnter",
    config = function()
      vim.schedule(function
        require("copilot.copilot_handler").start({ plugin_manager_path = vim.fn.expand "$HOME" .. "/.local/share/lunarvim/" })
      end)
    end,
 },
```

**Comment by zbirenbaum** [comment]
The reason this popped up is because there's more than one config option now, so it needs to be specified.

**Comment by opxop** [comment]
i dont really understand, sorry. now another message pops up
![image](https://user-images.githubusercontent.com/49778014/162554367-4b2f2bad-555a-4c91-9fc9-fa464bf8d5c3.png)

**Comment by opxop** [comment]
if i add `site/pack/packer/` like so

```
require("copilot.copilot_handler").start {
  -- plugin_manager_path = vim.fn.expand "$HOME" .. "/.local/share/lunarvim/",
  plugin_manager_path = vim.fn.expand "$HOME" .. "/.local/share/lunarvim/site/pack/packer",
}
```

the error message popped up when I entered insert mode

![image](https://user-images.githubusercontent.com/49778014/162554526-79aa1210-0e6e-405c-9bfe-32c906ad4326.png)

**Comment by zbirenbaum** [comment]
> if i add `site/pack/packer/` like so
> 
> ```
> require("copilot.copilot_handler").start {
>   -- plugin_manager_path = vim.fn.expand "$HOME" .. "/.local/share/lunarvim/",
>   plugin_manager_path = vim.fn.expand "$HOME" .. "/.local/share/lunarvim/site/pack/packer",
> }
> ```
> 
> the error message popped up when I entered insert mode
> 
> ![image](https://user-images.githubusercontent.com/49778014/162554526-79aa1210-0e6e-405c-9bfe-32c906ad4326.png)

Sorry, the config handler was doing some really weird stuff. I deleted everything and rewrote it properly. I tested out that snippet but with my own path and its working fine now.

**Comment by opxop** [comment]
that's working now, thanks for your help @zbirenbaum
