### ISSUE TITLE
Callback error when cycling through suggestions

### ISSUE THREAD

**Issue by pbdeuchler** [zbirenbaum/copilot.lua#154]
```
Error executing vim.schedule lua callback: ...e/pack/packer/opt/copilot.lua/lua/copilot/suggestion.lua:319: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...e/pack/packer/opt/copilot.lua/lua/copilot/suggestion.lua:319: in function 'get_suggestions_cycling_callback'
        ...e/pack/packer/opt/copilot.lua/lua/copilot/suggestion.lua:339: in function 'handler'
        ...w/Cellar/neovim/0.9.0/share/nvim/runtime/lua/vim/lsp.lua:1394: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Edit: Sorry for submitting this with no context. I get this seemingly randomly when cycling through suggestions. I'm not sure what triggers this, but it does seem to have to do with potentially cycling through suggestions when a request is in flight? The only reason I think so is because it happens more frequently when the suggestion is large, or is clearly using more context. But still pure conjecture.

**Comment by pbdeuchler** [comment]
Hmmmm, it might have something to do with keybinds. For some reason my `Tab` key stopped working when the error popped up. Got similar issues with `Esc` after I restarted.

**Comment by MunifTanjim** [comment]
What's the output of `:Copilot version`

**Comment by MunifTanjim** [comment]
How are you setting up the plugin?

**Comment by pbdeuchler** [comment]
Sorry for not responding, and awesome to see this get fixed! Thank you!
