### ISSUE TITLE
If <Tab> is set as the accept keymap, it is no longer possible to use it for normal tabs even when there are no suggestions

### ISSUE THREAD

**Issue by Vanclief** [zbirenbaum/copilot.lua#160]
I like to have `<Tab>` as my default accept mapping. However by setting it up to do that, it prevents me from using normally the `<Tab>` function even if there are no suggestions.

My ideal behavior would be that when there is a suggestion using `<Tab>` accepts it. When there is no suggestion `<Tab>` just inserts tabs.

Is this possible?

My config:
```
require('copilot').setup({
  ...
  suggestion = {
    enabled = true,
    auto_trigger = false,
    debounce = 75,
    keymap = {
      accept = "<Tab>",
      accept_word = false,
      accept_line = false,
      next = "<M-]>",
      prev = "<M-[>",
      dismiss = "<C-]>",
    },
  },
  ...
})
```

**Comment by MunifTanjim** [comment]
Check https://github.com/zbirenbaum/copilot.lua/discussions/153#discussioncomment-5701223
