### ISSUE TITLE
Suggestion is not completely shown when it takes up more than the end of the line

### ISSUE THREAD

**Issue by carmilso** [zbirenbaum/copilot.lua#161]
I'm facing an issue that I am sure is simple to fix, but I have spent some time trying it and I can't figure it out.

The problem comes when the suggestion is longer than what is left to reach the end of the line, as you can see in the following picture:

![copilot-1](https://user-images.githubusercontent.com/7313231/236247725-ce9b0332-9b6d-430c-8a73-efcb7ea072c4.png)

However, If I do accept the suggestion, this is what it should have appeared in the previous picture:

![copilot-2](https://user-images.githubusercontent.com/7313231/236248026-a2798f60-e7ac-4f60-a01f-bd916b481a58.png)

So as you can see, the suggestion isn't complete when it first appears, at least until I accept it. Any ideas?

**Comment by carmilso** [comment]
I see... Thanks for the answer. So do you think there may be some workaround to show the entire suggestion?

**Comment by MunifTanjim** [comment]
Unless Neovim supports it, nope. Also, I'm not sure if it's worth it. You can do one of the following:

- Just accept it the whole thing and then edit manually.
- Once your markdown file has a pattern, copilot will usually follow that. So, if all the lines in your markdown files are within 120 characters, copilot will give suggestion with
that line length.

**Comment by carmilso** [comment]
Okay, thanks. It's a bit annoying because in Vim you can see the full suggestion but I will accept it and then edit manually

**Comment by MunifTanjim** [comment]
Yeah, looks like vim's virtual text supports wrapping.

You can create a feature request for Neovim: https://github.com/neovim/neovim/issues

**Comment by carmilso** [comment]
> Yeah, looks like vim's virtual text supports wrapping.
> 
> You can create a feature request for Neovim: https://github.com/neovim/neovim/issues

I will. Thanks for the suggestion!

**Comment by carmilso** [comment]
@MunifTanjim wouldn't it be possible to use a keymap to move the Copilot's suggestion to a popup (like cmp) so it is fully shown?

**Comment by MunifTanjim** [comment]
Yep, that would be possible to implement.
