### ISSUE TITLE
Login verification did not respond.

### ISSUE THREAD

**Issue by j2501987804** [zbirenbaum/copilot.lua#167]
ENV
os:ubuntu22.04
nvim0.9
nodev18.16.0

[Screencast from 2023年05月10日 12时15分12秒.webm](https://github.com/zbirenbaum/copilot.lua/assets/41771911/da2b97e2-e836-4706-b288-c6775daac93f)

**Comment by MunifTanjim** [comment]
Can you log in with the official [copilot.vim](https://github.com/github/copilot.vim)? Might just be that it's a network issue and/or your ip is somehow blocked by github copilot service.

This is less likely to be an issue with this plugin.
