### ISSUE TITLE
How to logout or change github account?

### ISSUE THREAD

**Issue by jiu-chen** [zbirenbaum/copilot.lua#169]
Hi,

I login a wrong account by ":Copilot auth", I want to change to a new github account, I tried a lot of ways, including uninstall the plugin, all of them do not work.

Now everytime I type ":Copilot auth", it show "Authenticated as GitHub user: jiu-chen", but I want to use my other github accout which has copilot license.

Please kindly tell me how to loggout the github account.

Thanks.

**Comment by MunifTanjim** [comment]
<img width="282" alt="image" src="https://github.com/zbirenbaum/copilot.lua/assets/8050659/637bf523-96cb-445b-a5b9-8eeb9e952a90">

`:Copilot auth signout`

All the commands are available via autocomplete.
