### ISSUE TITLE
Auth failing due to self signed certificate in chain

### ISSUE THREAD

**Issue by thomascrha** [zbirenbaum/copilot.lua#174]
Were I work we have a man in the middle SSL 'security' feature built into our laptops. This requires trusting any self signed certs being used. I run neovim using WSL on windows and have added the cert to the default path /etc/ssl/certs - and have apt curl git and other packages to work with certificates - so from what i can tell is that node doesn't adhere to these settings. I found that the copilot.vim project has an option for doing exactly this - is this also implemented in this project or is there a way to provide this flag also ?

https://github.com/github/copilot.vim/blob/1358e8e45ecedc53daf971924a0541ddf6224faf/doc/copilot.txt#L85

Sorry I accidently opened this issue in the cmp repo (https://github.com/zbirenbaum/copilot-cmp/issues/73)

**Comment by thomascrha** [comment]
I was able to fix this issue by setting NODE_EXTRA_CA_CERTS to my cert bundle and it now works fine

**Comment by MunifTanjim** [comment]
> I found that the copilot.vim project has an option for doing exactly this - is this also implemented in this project or is there a way to provide this flag also ?

This plugin supports the same variable. You can just set:

```lua
vim.g.copilot_proxy_strict_ssl = false
```

Before calling `require("copilot").setup()`

**Comment by kdheepak** [comment]
I'm unable to get `Copilot auth` to succeed. The popup in neovim doesn't go away indefinitely after authentication on GitHub (even though the authentication on github is successful). The immediate next call to `:Copilot auth` prints the following error:

```
[Copilot] RPC[Error] code_name = unknown, code = 1001, message = "Could not log in with device flow on github.com: unable to get local issuer certificate"
```

I have `vim.g.copilot_proxy_strict_ssl = false`. I believe I have to pass in my corporate SSL certificate to some requests. Do you happen to know how I can go about doing that?

**Comment by Enqueued** [comment]
Been trying this as well but haven't been able to get around the cert issues.
I've set the `vim.g.copilot_proxy_strict_ssl = false` option but it still fails to authenticate with github. 
I've even attempted to set both curl and wget to strictly not use ssl but no dice.

> Notes:
> * IT wont give the cert
> * I'm on wsl
