### ISSUE TITLE
Option to dismiss copilot when leaving insert mode

### ISSUE THREAD

**Issue by RyanCarrier** [zbirenbaum/copilot.lua#179]
Would be great to have an option to auto dismiss copilot's suggestion when leaving insert mode.

Sometimes it will leave artifacts as I'm moving around making it hard to see what's written/what's underneath. Going into and our of insert mode solves it, (or dismissing manually)

**Comment by MunifTanjim** [comment]
> Would be great to have an option to auto dismiss copilot's suggestion when leaving insert mode.

It already does so.

https://github.com/zbirenbaum/copilot.lua/blob/77e3a4907928f0813024e573b882dc879dfc0c6b/lua/copilot/suggestion.lua#L486-L488

https://github.com/zbirenbaum/copilot.lua/blob/77e3a4907928f0813024e573b882dc879dfc0c6b/lua/copilot/suggestion.lua#L521-L525

Let me know if you can reproduce when it doesn't work.

**Comment by RyanCarrier** [comment]
https://github.com/zbirenbaum/copilot.lua/assets/9389452/60d94f83-0650-46ba-bf5f-3250f15c5f82

**Comment by MunifTanjim** [comment]
What happens when you run `:redraw` the the virtual text stays back after leaving insert mode? Does it disappear?

**Comment by RyanCarrier** [comment]
Virtual text still stays after running :redraw

**Comment by MunifTanjim** [comment]
Just to make sure, is it still the same if you do `:redraw!` (notice the bang at the end, it redraws entire screen).

**Comment by MunifTanjim** [comment]
Also, do you use `<C-c>` to exit insert mode by any chance?

**Comment by RyanCarrier** [comment]
No change with :redraw!
Yes I do use C-c....

**Comment by MunifTanjim** [comment]
`<C-c>` does not trigger the `InsertLeave` autocmd.

So you should:
- either remap `<C-c>` to `<C-[>` or `<Esc>` (can have unforeseen consequences)
- or use `<C-[>` or `<Esc>` for leaving insert mode
- or remap `<C-c>` to also call `require("copilot.suggestion").dismiss()`
