### ISSUE TITLE
Lost keymaps for InsertLeave

### ISSUE THREAD

**Issue by cmac4603** [zbirenbaum/copilot.lua#181]
After installing copilot.lua, I've lost my custom keymappings for InsertLeave, and it seems I've lost `<Esc>` in particular for leaving insert mode:

- `jk` would exit insert mode to normal, mapped to `<Esc>`
- `<C-s>` would exit insert mode to normal `<Esc>:<CR>` and write to file (now it literally types out `:w<CR>`)

I haven't written this anywhere in my copilot config that I can see, and I can fix all of these by changing `<Esc>` to `<C-c>` in my mappings, but I was wondering if anyone could shed some light as to why `<Esc>` has stopped working? Reading the docs there wasn't any mention of this.

```lua
return {
  "zbirenbaum/copilot.lua",
  cmd = "Copilot",
  event = "InsertEnter",
  config = function()
    require("copilot").setup({
      panel = {
        enabled = true,
        auto_refresh = true,
        keymap = {
          jump_prev = "[[",
          jump_next = "]]",
          accept = "<CR>",
          refresh = "gr",
          open = "<M-CR>"
        },
        layout = {
          position = "bottom", -- | top | left | right
          ratio = 0.4
        },
      },
      filetypes = {
        yaml = true,
        markdown = true,
        help = true,
        gitcommit = true,
        gitrebase = true,
        qf = true,
        hgcommit = true,
        svn = true,
        cvs = true,
        ["."] = true,
      },
      suggestion = {
        enabled = true,
        auto_trigger = false,
        debounce = 75,
        keymap = {
          accept = "<c-j>",
          next = "<c-]>",
          prev = "<c-[>",
          dismiss = "jk",
        },
      },
    })
  end,
}
```

**Comment by cmac4603** [comment]
Nvm, after hours looking then posting this, realised it was because I was remapping `CTRL-[` which in neovim is equivalent to `<Esc>`. Going to get more coffee now.

**Comment by choznerol** [comment]
> Nvm, after hours looking then posting this, realised it was because I was remapping `CTRL-[` which in neovim is equivalent to `<Esc>`. Going to get more coffee now.

Thanks so much for sharing this! The default `<M-[>` outputs a `“` for me on Mac, so I also configured `<C-[>`. I was so confused when `<Esc>` stop working 😅.

**Comment by martimolanes** [comment]
thanks so much!
