### ISSUE TITLE
Ignore dismiss mapping when suggestion isn't visible

### ISSUE THREAD

**Issue by MariaSolOs** [zbirenbaum/copilot.lua#189]
I've mapped `suggestion.keymap.dismiss` to `'/'`, but now that prevents me from typing `'/'` in insert mode. How can I properly enable the command only if a suggestion is visible?

**Comment by MariaSolOs** [comment]
nvm, I fixed it with the following:
```lua
vim.keymap.set('i', '/', function()
  if copilot.is_visible() then
    copilot.dismiss()
    return '<Ignore>'
  else
    return '/'
  end
end, { expr = true })
```

That being said, I believe that such logic should be integrated into the plugin :)

**Comment by MariaSolOs** [comment]
@MunifTanjim Would you be against me preparing a PR for this? :)

**Comment by MunifTanjim** [comment]
Nope. I'm open to merging a PR for this.
