### ISSUE TITLE
`lsp.log`: copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false

### ISSUE THREAD

**Issue by thenbe** [zbirenbaum/copilot.lua#194]
```
[WARN][2023-07-02 15:17:07] ...lsp/handlers.lua:134	"The language server copilot triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

I keep getting this warning in `lsp.log`.

**Comment by MunifTanjim** [comment]
Please report this to:
- https://github.com/github/copilot.vim
- https://github.com/orgs/community/discussions/categories/copilot

This plugin uses the offical lsp server. We can't change its behavior.

**Comment by thenbe** [comment]
Done. https://github.com/orgs/community/discussions/60285

**Comment by beyourselfm** [comment]
Most likely it's the node version, update the node version to 18 or above.
