### ISSUE TITLE
:Copilot auth crashing

### ISSUE THREAD

**Issue by SiKreuz** [zbirenbaum/copilot.lua#196]
I installed [zirbenbaum/copilot.lua](https://github.com/zbirenbaum/copilot.lua) with [wbthomason/packer.nvim](https://github.com/wbthomason/packer.nvim) and then tried to authenticate with `:Copilot auth`. This is what I get on my console. Reinstalling didn't work. The original [github/copilot.vim](https://github.com/github/copilot.vim) seems to work.

```console
Error executing Lua callback: ...ite/pack/packer/start/copilot.lua/lua/copilot/client.lua:130: copilot.setup is not called yet
stack traceback:
        [C]: in function 'error'
        ...ite/pack/packer/start/copilot.lua/lua/copilot/client.lua:130: in function 'use_client'
        ...im/site/pack/packer/start/copilot.lua/plugin/copilot.lua:45: in function <...im/site/pack/packer/start/copilot.lua/plugin/copilot.lua:8>
```

**Comment by MunifTanjim** [comment]
You haven't provided any code showing how you set up the plugin.

Did you follow https://github.com/zbirenbaum/copilot.lua#setup-and-configuration?

Did you call `require("copilot").setup()`?

**Comment by SiKreuz** [comment]
I'm sure I did exactly that. For some reason it didn't work, but does now. I'm a bit confused but as long as it is working now. Sorry for the redundant issue.
