### ISSUE TITLE
LSP functionality detects incorrect root directory

### ISSUE THREAD

**Issue by jolars** [zbirenbaum/copilot.lua#212]
I use LazyVim, which includes several key mappings, for instance for searching in the root directory, that rely on the LSP client detecting the correct root directory. This is the function LazyVim uses: https://github.com/LazyVim/LazyVim/blob/a72a84972d85e5bbc6b9d60a0983b37efef21b8a/lua/lazyvim/util/init.lua#L56-L89

But it seems like the Copilot LSP server is reporting my home directory as the root directory for every file it attaches to. This is for instance the result of calling `:LspInfo` from a `Makefile` in one of my projects.

```
 Language client log: /home/<user>/.local/state/nvim/lsp.log
 Detected filetype:   make
 
 1 client(s) attached to this buffer: 
 
 Client: copilot (id: 1, bufnr: [26, 24])
 	filetypes:       
 	autostart:       false
 	root directory:  /home/<user>
 	cmd:             node /home/<user>/.local/share/nvim/lazy/copilot.lua/copilot/index.js

```

So when Copilot is the only LSP server attached to a file, I end up searching directly in my home directory instead of the project directory.

This is the default setup LazyVim uses for copilot, which I use: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/coding/copilot.lua

If I disable the plugin, then everything works fine because lazyvim then just uses cwd.

Maybe it would be possible to expose a `root_dir` setting just like many of the servers in lspconfig do (https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md)?

A possible interface might be:

```
require('copilot').setup({
  server_opts_overrides = {
    root_dir = require("lspconfig.util").root_pattern(".git"),
  },
})
```

Or I guess the server could just not report the root directory, or default to `vim.loop.cwd()`. I'm not sure exactly if that would work.

**Comment by MunifTanjim** [comment]
>  default to `vim.loop.cwd()`

https://github.com/zbirenbaum/copilot.lua/blob/2c942f33ba5c621c906e625e00a1bb504b65e2f0/lua/copilot/client.lua#L183

**Comment by jolars** [comment]
> > default to `vim.loop.cwd()`
> 
> https://github.com/zbirenbaum/copilot.lua/blob/2c942f33ba5c621c906e625e00a1bb504b65e2f0/lua/copilot/client.lua#L183

Thanks, sorry, missed that. 

But why is the server reporting `home/<user>` as root directory in that case? In the same buffer, running `:lua vim.print(vim.loop.cwd())` gives me `home/<user>/<project>`.

**Comment by jolars** [comment]
I don't think it makes sense to set `root_dir = vim.loop.cwd()`. I suppose that `setup()` probably doesn't run for every new buffer, right? In which case it would just use the output of `vim.loop.cwd()` at whatever time it was called.

I'm looking at other configurations at lspconfig now, and I'm thinking it should probably be

```lua
root_dir = require("lspconfig.util").find_git_ancestor
```

I'll test this and submit a PR if it works.

**Comment by MunifTanjim** [comment]
> But why is the server reporting home/<user> as root directory in that case? In the same buffer, running :lua vim.print(vim.loop.cwd()) gives me home/<user>/<project>.

It's set when you open vim. Are you opening vim on your home directory and later changing the directory?

**Comment by jolars** [comment]
Yes, you're right. That's what's happening. If I run neovim from the project directory, it's set appropriately.
