### ISSUE TITLE
Put cursor at end of accepted multi-line suggestion

### ISSUE THREAD

**Issue by b0o** [zbirenbaum/copilot.lua#216]
I'm not sure if this is a bug or the intended behavior, but when I accept a multi-line suggestion, the cursor is placed at the end of the current line, rather than the end of the inserted suggestion. This is especially annoying when the suggestion is missing the closing paren/bracket, as in the gif below.

Is this intended? If so, is there a way to change the behavior? VSCode behaves in the way I would expect.

![2023-10-11_15-18-20_Alacritty](https://github.com/zbirenbaum/copilot.lua/assets/21299126/01d29ccc-5dfd-40fb-aabe-994fa5940940)

**Comment by MunifTanjim** [comment]
I think something broke recently. This used to work as expected before.

**Comment by MunifTanjim** [comment]
@b0o can you please share the output of `:Copilot version`?

**Comment by b0o** [comment]
Sure:

```
Neovim 0.10.0-dev-1324+gc3d21ad1bc
copilot.vim 1.10.3
copilot.lua 1a8032ae496916ccc7a7a52ee79194fbef29f462
copilot/dist/agent.js 1.110.389
Node.js 20.6.1
```

**Comment by MunifTanjim** [comment]
This is probably caused by https://github.com/neovim/neovim/pull/24901
