### ISSUE TITLE
The <Tab> keymap for accepting suggestion fails to insert a tabulation when there is no suggestion available.

### ISSUE THREAD

**Issue by sebui** [zbirenbaum/copilot.lua#217]
When the accept function is mapped to the `<Tab>` keymap, tabulation is not inserted when there is no suggestion available.
Unlike [github/copilot.vim](https://github.com/github/copilot.vim), copilot.nvim effectively inserts a tab even when there is no suggestion available.

The cause of this problem lies in the early void return statement found in all accept functions:

https://github.com/zbirenbaum/copilot.lua/blob/1a8032ae496916ccc7a7a52ee79194fbef29f462/lua/copilot/suggestion.lua#L444-L447

A potential solution to this issue, although it requires further testing to ensure there are no unintended side effects, could involve making the following code modification:
```lua
  if not suggestion or vim.fn.empty(suggestion.text) == 1 then
    local key = config.get("suggestion").keymap.accept
    key = vim.api.nvim_replace_termcodes(key, true, false, true)
    vim.fn.feedkeys(key, "n")
    return
  end
```

**Comment by MunifTanjim** [comment]
This is expected behavior. Check:
- https://github.com/zbirenbaum/copilot.lua/discussions/153
- https://github.com/zbirenbaum/copilot.lua/issues/160
- https://github.com/zbirenbaum/copilot.lua/issues/91

**Comment by sebui** [comment]
Oh sorry did not see those threads
