### ISSUE TITLE
[Bug] `cmd` override in `copilot.lua` setup doesn't produce any effect

### ISSUE THREAD

**Issue by pidgeon777** [zbirenbaum/copilot.lua#22]
My `packer.nvim` config:

```lua
    {
      "zbirenbaum/copilot.lua",
      -- event = {"VimEnter"},
      after = "nvim-cmp",
      requires = {"zbirenbaum/copilot-cmp"},
      config = function()
        local cmp_source = { name = "copilot", group_index = 2 }
        table.insert(lvim.builtin.cmp.sources, cmp_source)
        local plugin_manager_path = require("lvim.utils").join_paths(get_runtime_dir(), "site", "pack", "packer")
        vim.defer_fn(function()
          require("copilot").setup {
            plugin_manager_path = plugin_manager_path,
            server_opts_overrides = {
              cmd = { "node", require("copilot.util").get_copilot_path(plugin_manager_path) }
            },
          }
        end, 100)
      end,
    },
```

As a result, `copilot.lua` starts a LSP server using the default `cmd` string.

This also applies to other `server_opts_overrides` fields such as `trace` and `name`.

**Comment by zbirenbaum** [comment]
> My `packer.nvim` config:
> 
> 
> 
> ```lua
> 
>     {
> 
>       "zbirenbaum/copilot.lua",
> 
>       -- event = {"VimEnter"},
> 
>       after = "nvim-cmp",
> 
>       requires = {"zbirenbaum/copilot-cmp"},
> 
>       config = function()
> 
>         local cmp_source = { name = "copilot", group_index = 2 }
> 
>         table.insert(lvim.builtin.cmp.sources, cmp_source)
> 
>         local plugin_manager_path = require("lvim.utils").join_paths(get_runtime_dir(), "site", "pack", "packer")
> 
>         vim.defer_fn(function()
> 
>           require("copilot").setup {
> 
>             plugin_manager_path = plugin_manager_path,
> 
>             server_opts_overrides = {
> 
>               cmd = { "node", require("copilot.util").get_copilot_path(plugin_manager_path) }
> 
>             },
> 
>           }
> 
>         end, 100)
> 
>       end,
> 
>     },
> 
> ```
> 
> 
> 
> As a result, `copilot.lua` starts a LSP server using the default `cmd` string.
> 
> 
> 
> This also applies to other `server_opts_overrides` fields such as `trace` and `name`.

Huh, that's a major problem. I didn't notice it when using overrides on my dev branch though. I'll look into, thanks for letting me know.
