### ISSUE TITLE
auto login

### ISSUE THREAD

**Issue by janvanveldhuizen** [zbirenbaum/copilot.lua#221]
Every time I start nvim, I have to use the :copilot auth command.  Where do I need to add this command in order to run it automatically at login?

**Comment by MunifTanjim** [comment]
You need to only run it once. You shouldn't have to run it each time you start neovim. Something's wrong on your machine.

**Comment by janvanveldhuizen** [comment]
I have been testing a bit with it today. It looks like it is related to the lazy loading of the plugin. I just need to have a bit of patience. Or can I switch off lazy loading for this particular plugin to be sure it is active? Or is there any notification possible to give an alert when the plugin is ready for use?

**Comment by MunifTanjim** [comment]
How are you lazy loading it? If you follow the instructions in `README.md`, it should work as expected.

**Comment by janvanveldhuizen** [comment]
Yes. I reinstalled the whole thing, and it works perfectly now.
