### ISSUE TITLE
Copilot fails to start since latest changes

### ISSUE THREAD

**Issue by pavkam** [zbirenbaum/copilot.lua#225]
I keep getting `Client N quit with exit code 1 and signal 0` notifications repeatedly when Copilot tries to start up.
The latest good commit is `1a8032ae496916ccc7a7a52ee79194fbef29f462`.

MacOS 13.5.2

Any other details I can provide?

**Comment by pavkam** [comment]
Right, seems to be related to the node version. I was using `node 16`. It works on `node 18`. Maybe add a documentation note in the readme to make sure others don't trip on this.

**Comment by MunifTanjim** [comment]
It should show a warning with latest commit https://github.com/zbirenbaum/copilot.lua/commit/688762a3999eeee54b78f447719854f52672ec02
