### ISSUE TITLE
Only get 1-line suggestions for JS/TS (panel shows entire suggestion)

### ISSUE THREAD

**Issue by dseravalli** [zbirenbaum/copilot.lua#229]
It's happening in TS/JS files consistently, but not in Python or Ruby files. I have tried both with and without the cmp plugin and the behavior is the same.

Installed with Lazy like this:
```lua
  {
    "zbirenbaum/copilot.lua",
    cmd = 'Copilot',
    event = 'InsertEnter',
    config = function()
      require("copilot").setup({
        suggestion = {
          auto_trigger = true
        }
      })
    end
  },
 ```
 
 or like this:
 ```lua
  {
    "zbirenbaum/copilot.lua",
    cmd = 'Copilot',
    event = 'InsertEnter',
    config = function()
      require("copilot").setup({
        suggestion = { enabled = false },
        panel = { enabled = false },
      })
    end
  },
  {
    "zbirenbaum/copilot-cmp",
    config = function()
      require("copilot_cmp").setup()
    end
  },
```

What I see in insert mode:
![Screenshot-2023-10-31-18 28 43](https://github.com/zbirenbaum/copilot.lua/assets/1758219/493bb5cf-10b2-44cc-bc84-bbee376dfe8e)

The panel on the same line:
![Screenshot-2023-10-31-18 28 30](https://github.com/zbirenbaum/copilot.lua/assets/1758219/5609b6cb-fe6e-4b61-9ba7-587a6eec0927)

**Comment by MunifTanjim** [comment]
Try updating to the latest version.

Beside that, we can't control what suggestion Copilot generates. If the suggestion is not satisfactory, you can give feedback here: https://github.com/orgs/community/discussions/categories/copilot

**Comment by MunifTanjim** [comment]
Copilot has separate APIs for generating codes for Panel and Suggestion. That's why they're different. The editor plugin just shows whatever Copilot generates.
