### ISSUE TITLE
not getting any sources on `cmp` from `copilot.lua`

### ISSUE THREAD

**Issue by marcelarie** [zbirenbaum/copilot.lua#24]
I can't get the source on `cmp` for `copilot.lua`, I debugged the sources that arrive at the `cmp` setup and there is no source coming from `copilot.lua` so the error should come from this plugin (I think…).

 `copilot.vim` works and the user auth works correctly.

I tried to create a minimal config, but I can't get it to work, here is the minimal config:

```lua
-- this template is borrowed from nvim-lspconfig
local on_windows = vim.loop.os_uname().version:match "Windows"

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir
if on_windows then
	temp_dir = vim.loop.os_getenv "TEMP"
else
	temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
	-- only add other plugins if they are necessary to reproduce the issue
	require("packer").startup {
		{
			"wbthomason/packer.nvim",
			{ "neovim/nvim-lspconfig" },
			{ "neovim/nvim-lsp" },
			{ "hrsh7th/nvim-cmp" },
			{ "hrsh7th/cmp-nvim-lsp" },
			{ "github/copilot.vim" }, -- needed for the auth
			{
				"zbirenbaum/copilot.lua",
				event = "VimEnter",
				config = function()
					vim.defer_fn(function()
						require("copilot").setup {}
					end, 100)
				end,
			},
			{
				"zbirenbaum/copilot-cmp",
				after = { "copilot.lua", "nvim-cmp" },
			},
			{ "williamboman/nvim-lsp-installer" },
		},
		config = {
			package_root = package_root,
			compile_path = compile_path,
		},
	}
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system {
		"git",
		"clone",
		"https://github.com/wbthomason/packer.nvim",
		install_path,
	}
	load_plugins()
	require("packer").sync()
else
	load_plugins()
	require("packer").sync()
end

vim.keymap.set("n", "<Space>w", ":w<cr>")
vim.keymap.set("n", "<Space>q", ":q<cr>")

require "lspconfig"

local cmp = require "cmp"
local kind = cmp.lsp.CompletionItemKind

-- vim.o.completeopt = "menu,menuone,noselect"
vim.opt.completeopt = { "menu", "menuone", "noselect" }

vim.cmd "set shortmess+=c"
vim.cmd "let g:completion_matching_strategy_list = ['exact', 'substring', 'fuzzy', 'all']"

cmp.setup {
	mapping = {
		["<C-n>"] = cmp.mapping(cmp.mapping.select_next_item(), { "i", "c" }),
		["<C-p>"] = cmp.mapping(cmp.mapping.select_prev_item(), { "i", "c" }),
		["<C-d>"] = cmp.mapping(cmp.mapping.scroll_docs(-4), { "i", "c" }),
		["<C-f>"] = cmp.mapping(cmp.mapping.scroll_docs(4), { "i", "c" }),
		["<C-e>"] = cmp.mapping {
			i = cmp.mapping.abort(),
			c = cmp.mapping.close(),
		},
		["<CR>"] = cmp.mapping.confirm {
			select = true,
			behavior = cmp.ConfirmBehavior.Replace,
		},
	},
	experimental = { ghost_text = true },
	sources = {
		{ name = "copilot" },
		{ name = "nvim_lsp", max_item_count = 5 },
	},
}

require("nvim-lsp-installer").setup {}
```

In my configuration, `cmp` works with all the other sources without any problem.

**Comment by kozer** [comment]
Same problem as well. No updates at all. Not sure if the problem lies to my recent update on neovim or something else.
Altghough it seems copilot is attaching properly on the buffer.

**Comment by marcelarie** [comment]
> Same problem as well. No updates at all. Not sure if the problem lies to my recent update on neovim or something else. Altghough it seems copilot is attaching properly on the buffer.

![Screenshot 2022-05-16 at 14 55 58](https://user-images.githubusercontent.com/62728887/168597363-470dcd50-9de4-419e-a844-252f2bc3a177.png)

Same, and I tested `copilot.vim` and it works.

**Comment by marcelarie** [comment]
Might be a `copilot-cmp` error. I got this on startup:

![Screenshot 2022-05-16 at 18 13 02](https://user-images.githubusercontent.com/62728887/168637666-a49b346e-65a9-468f-8379-47350239293a.png)
```
Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:142: Vim(source):E484: Can'
t open file /home/marcel/.local/share/nvim/site/pack/packer/opt/copilot-cmp/after/plugin/copilot_cmp.lua
Please check your config for correctness
```

**Comment by zbirenbaum** [comment]
This is very strange, are both of you on the same platform? 

The cmp source comes from copilot-cmp so it would likely be an issue in there, unless one of you has LspInfo not showing copilot

**Comment by zbirenbaum** [comment]
> The issue occurs on my work MacBook running macOS and on my ThinkPad with Linux.

That's very helpful, thank you!

**Comment by rebelot** [comment]
I am experiencing the same. macOS, compulsively running on latest nvim/cmp versions

**Comment by kozer** [comment]
I'm on linux. Arch distro more specific

**Comment by wizard-28** [comment]
Same issue here. I'm on Pop!_OS

**Comment by Hunter-Thompson** [comment]
+1 running arch here.

```
 Client: copilot (id: 3, pid: 82381, bufnr: [1, 8])
 	filetypes:       
 	autostart:       true
 	root directory:  /home/hunter/smallcase/cdk-eks-cluster-module
 	cmd:             node /home/hunter/.local/share/nvim/site/pack/packer/opt/copilot.lua/copilot/index.js
```

**Comment by zbirenbaum** [comment]
What I don't get is why I can't seem to trigger this on either of my arch systems. Can anyone with a bit more technical knowledge edit the files in copilot-cmp to get a better idea of exactly where it is that this error occurs?

**Comment by johnf** [comment]
@zbirenbaum I straced the copilot process (nothing was coming up in the logs and I can see)
```
write(1, "{\"jsonrpc\":\"2.0\",\"method\":\"LogMessage\",\"params\":{\"level\":3,\"message\":\"
[ERROR] [fetch] [2022-05-18T00:42:30.479Z] Unhandled status from server:,466,Please upgrade your Copilot extension to continue using this service.\\n\",\"metadataStr\":\"
[ERROR] [fetch] [2022-05-18T00:42:30.479Z]\",\"extra\":[\"Unhandled status from server:\",\"466\",\"Please upgrade your Copilot extension to continue using this service.\\n\"]}}", 402) = 402
```

I noticed this https://github.com/github/feedback/discussions/16423 so I suspect something has changed on copilot back end and this is related

**Comment by zbirenbaum** [comment]
> @zbirenbaum I straced the copilot process (nothing was coming up in the logs and I can see)
> 
> ```
> write(1, "{\"jsonrpc\":\"2.0\",\"method\":\"LogMessage\",\"params\":{\"level\":3,\"message\":\"
> [ERROR] [fetch] [2022-05-18T00:42:30.479Z] Unhandled status from server:,466,Please upgrade your Copilot extension to continue using this service.\\n\",\"metadataStr\":\"
> [ERROR] [fetch] [2022-05-18T00:42:30.479Z]\",\"extra\":[\"Unhandled status from server:\",\"466\",\"Please upgrade your Copilot extension to continue using this service.\\n\"]}}", 402) = 402
> ```
> 
> I noticed this [github/feedback#16423](https://github.com/github/feedback/discussions/16423) so I suspect something has changed on copilot back end and this is related

I just updated the copilot agent to the latest version, so hopefully that fixes things. If it doesn't I'll go into copilot.vim and see if any api changes of note were made.

**Comment by johnf** [comment]
@zbirenbaum I'm now seeing
read(0, "Content-Length: 300\r\n\r\n{\"params\":{\"contentChanges\":[{\"rangeLength\":0,\"range\":{\"start\":{\"line\":43,\"character\":9},\"end\":{\"line\":43,\"character\":9}},\"text\":\"n\"}],\"textDocument\":{\"uri\":\"file:\\/\\/\\/home\\/johnf\\/work\\/gladly\\/mobile\\/src\\/screens\\/feed\\/Home.tsx\",\"version\":45}},\"method\":\"textDocument\\/didChange\",\"jsonrpc\":\"2.0\"}", 65536) = 323
read(0, "Content-Length: 6579\r\n\r\n{\"params\":{\"doc\":{\"path\":\"\\/home\\/johnf\\/work\\/gladly\\/mobile\\/src\\/screens\\/feed\\/Home.tsx\",\"position\":{\"line\":43,\"character\":10},\"languageId\":\"typescriptreact\",\"tabsize\":2,\"relativePath\":\"src\\/screens\\/feed\\/Home.tsx\",\"indentsize\":2,\"source\":\"import React, { useEffect, useState } from 'react';\\n\\nimport VersionCheck from 'react-native-version-check';\\nimport { getBundleId } from 'react-native-device-info';\\nimport withObservables from '@nozbe\\/with-observables';\\n\\nimpo"..., 65536) = 6603
epoll_wait(13, [], 1024, 0)             = 0
write(1, "Content-Length: 116\r\n\r\n", 23) = 23
write(1, "{\"jsonrpc\":\"2.0\",\"id\":19,\"error\":{\"code\":-32602,\"message\":\"Invalid params: /doc must have required property 
```
I then added
```
uri = 'file://' .. vim.api.nvim_buf_get_name(0),
```

to get_completion_parameters and that seemed to fix it.

But on that note, congratulations and go and enjoy your graduation, we can all wait till next week :grinning:

**Comment by marcelarie** [comment]
yes no problem take the time you need

**Comment by marcelarie** [comment]
@johnf where did you add the `uri` parameter? :)

**Comment by johnf** [comment]
@marcelarie I've created a pull request https://github.com/zbirenbaum/copilot.lua/pull/25

**Comment by zbirenbaum** [comment]
I think this can be closed thanks to @johnf!

If the issue persists please let me know, but I did some pretty thorough testing and it seems mostly fine.

Couple of quick side notes:
1. I've noticed longer response times for copilot. This appears to be a (mostly) microsoft issue, but is worsened by some aspects of nvim-cmp's source handling, which isn't meant to be used with high latency completions like the ones provided
2. Additionally, the long requested feature of adding copilot completions on a newline seemed to be working earlier, but without a starting character the nvim-cmp menu refuses to show. I'm working on a larger patch to both copilot_cmp and nvim-cmp to try and address this, but I can't promise the nvim-cmp one (which is slightly more impactful) will be merged
3. I just opened a PR hrsh7th/nvim-cmp#1003 which will allow me to add a custom `kind` for copilot, so you can have something like this instead of `snippet`
![2022-05-20-021432_866x207_scrot](https://user-images.githubusercontent.com/32016110/169464684-d64d4752-5780-4701-82d3-3275737e624c.png)
