### ISSUE TITLE
Perform Node version check

### ISSUE THREAD

**Issue by BSFishy** [zbirenbaum/copilot.lua#242]
After setting up my Neovim config on my laptop, I noticed I kept getting warnings like `Client [number] quit with exit code 2 and signal 0`. At first I was quite lost, since my config is based off of LazyVim and I'm quite new to Vim, so I didn't really know where to start to troubleshoot, but I wrote a little bit of code and noticed I wasn't getting Copilot suggestions.

To make a long story short, I realized my default Node version was v16. Fixing default Node version to v20 fixed it, but the warning message was difficult to figure out. I (maybe naively) feel like a quick `node --version` check before calling `node` would make the experience a little be nicer. I also recognize that the README specifically says that Node needs to be > 18.x, so feel free to close this if it's out of scope.

Potentially related: #232

**Comment by MunifTanjim** [comment]
Should be fixed with https://github.com/zbirenbaum/copilot.lua/commit/3665ed0f3ef3ad68673df7195789d134d0d1fdb0
