### ISSUE TITLE
Clarification on Code Shared with GitHub for Context

### ISSUE THREAD

**Issue by luzik** [zbirenbaum/copilot.lua#245]
Could you please provide detailed information (possibly in the README) regarding what part of my code is sent to GitHub for context purposes? I am particularly interested in understanding whether it's just a portion of my current buffer, the entire file, or all open files that are shared. This clarification will greatly help in ensuring proper context is set for operations and maintaining code privacy.

**Comment by MunifTanjim** [comment]
This plugin is just a wrapper for the LSP Server from https://github.com/github/copilot.vim.

And these questions should go to https://github.com/orgs/community/discussions/categories/copilot.

It's safe to assume, when Copilot is attached to a buffer it can read the whole buffer. Just like any other LSP Server.
