### ISSUE TITLE
Feature Request - Assistance with Code Debugging Using Copilot

### ISSUE THREAD

**Issue by luzik** [zbirenbaum/copilot.lua#246]
I am unsure, but I didn't find any way to ask your copilot to fix my pice of code within given error message or my suggestion. Is there any way to do that ? If no please consider adding such a feature.

**Comment by MunifTanjim** [comment]
If https://github.com/github/copilot.vim doesn't support that feature, this plugin won't be able to support it either.

This feature request should go to https://github.com/orgs/community/discussions/categories/copilot
