### ISSUE TITLE
Copilot should allow enable even if the filetypes are disabled by default.

### ISSUE THREAD

**Issue by fishman** [zbirenbaum/copilot.lua#248]
For security reasons it should be possible to only toggle it for the current file even if all filetypes are set to disable.

Copilot enable does not currently enable copilot in that case but should.

**Comment by fishman** [comment]
I guess it's possible to do that with Copilot! enable. The problem is that when that option is used it will force enable it for all subsequent files as well.

This isn't the behaviour of the normal plugin. You can enable it per file, but it will still honour the filetype settings for subsequent files.

**Comment by MunifTanjim** [comment]
> I guess it's possible to do that with Copilot! enable. The problem is that when that option is used it will force enable it for all subsequent files as well.

Where did you find that behavior?

**Comment by MunifTanjim** [comment]
Use `:Copilot! attach` for force attaching copilot to the current buffer.
