### ISSUE TITLE
How do I auth with a different user?

### ISSUE THREAD

**Issue by jpericavcc** [zbirenbaum/copilot.lua#260]
I've been authenticated as one user and would like to authenticate as a different user.
```
:Copilot auth
```
shows a message that I am authenticated

```
:Copilot panel
```
shows "RPC[Error] code_name = unknown, code = 1000, message = Not authenticated: NotAuthorized"

How can I login so that I am able to login with the other user?

**Comment by MunifTanjim** [comment]
- https://github.com/zbirenbaum/copilot.lua/issues/176
- https://github.com/zbirenbaum/copilot.lua/issues/169
- https://github.com/zbirenbaum/copilot.lua/discussions/122
- https://github.com/zbirenbaum/copilot.lua/discussions/120
