### ISSUE TITLE
Need logout command

### ISSUE THREAD

**Issue by hongminhcbg** [zbirenbaum/copilot.lua#263]
Context:
- I successfully log in with an old account.
- I uninstall the plugin.
- I use a new GitHub account.
- I reinstall the plugin. Every time I run "Copilot auth," the plugin automates login with my old account.

I have to work around with edit your code
![photo_2024-01-31 10 39 31](https://github.com/zbirenbaum/copilot.lua/assets/47794920/ca64c068-f805-4553-87e3-7aecbd5ba5c1)

**Comment by MunifTanjim** [comment]
Please search before creating issues:
- https://github.com/search?q=repo%3Azbirenbaum%2Fcopilot.lua+signout&type=issues
- https://github.com/search?q=repo%3Azbirenbaum%2Fcopilot.lua+signout&type=discussions
