### ISSUE TITLE
Stuck suggestion ghost on window change

### ISSUE THREAD

**Issue by blauweb** [zbirenbaum/copilot.lua#268]
Hi,

If I change the window once a suggestion has appeared next to my cursor, a ghost of that suggestion stays in that line of code and doesn't go away until I reset vim.

Edit:
The issue happens specifically when I switch the focus to a different window (inside nvim) by mouse, while in insert mode; this does not happen if I change focus to a different app, or if I exit insert mode first and then change the focus.

Environment:
Ubuntu 22.04
Gnome 42
Neovim with Lazyvim.

![image](https://github.com/zbirenbaum/copilot.lua/assets/38893376/af38a35e-36e7-4330-bf1e-9778739ee4b6)

**Comment by MunifTanjim** [comment]
Does this bug happen on 71382c2efec76647287d46a4fbe0ec8c9809e2ee?

I think some things might be broken because https://github.com/zbirenbaum/copilot.lua/pull/262 was merged without making necessary changes.

**Comment by zbirenbaum** [comment]
My bad, I'll fix this and revert that commit for now

**Comment by zbirenbaum** [comment]
> Does this bug happen on 71382c2efec76647287d46a4fbe0ec8c9809e2ee?
> 
> 
> 
> I think some things might be broken because https://github.com/zbirenbaum/copilot.lua/pull/262 was merged without making necessary changes.

262 just updated the copilot dist. The diff shows a `postion` being changed to `position` for that commit. Are they related?

**Comment by MunifTanjim** [comment]
I just meant that https://github.com/github/copilot.vim has other changes in these commits:
- https://github.com/github/copilot.vim/commit/1a55183ef9347d6f420406a3746474b6b9fb9ef5
- https://github.com/github/copilot.vim/commit/49e0348bfb913fae63ca5ddb987a8bccd193da86
- https://github.com/github/copilot.vim/commit/a8142d44602f1b3f7b5c03c52b55f8f5d3453bf0
- https://github.com/github/copilot.vim/commit/22fd9542e3c47552abab5e685fefd760e4f405b2

Since those were not ported over in copilot.lua, that could potentially cause issues.

That's why I asked if the same issue existed before merging #262 .

**Comment by zbirenbaum** [comment]
> I just meant that https://github.com/github/copilot.vim has other changes in these commits:
> 
> - https://github.com/github/copilot.vim/commit/1a55183ef9347d6f420406a3746474b6b9fb9ef5
> 
> - https://github.com/github/copilot.vim/commit/49e0348bfb913fae63ca5ddb987a8bccd193da86
> 
> - https://github.com/github/copilot.vim/commit/a8142d44602f1b3f7b5c03c52b55f8f5d3453bf0
> 
> - https://github.com/github/copilot.vim/commit/22fd9542e3c47552abab5e685fefd760e4f405b2
> 
> 
> 
> Since those were not ported over in copilot.lua, that could potentially cause issues.
> 
> 
> 
> That's why I asked if the same issue existed before merging #262 .

Ah got it, I'll look those over and make any of the changes that are relevant.

**Comment by blauweb** [comment]
Thank you for your reply and interest in my issue.
If I read your comment correctly, I do not think this is related to #262 , but I can't say for 100% sure, because I just started to find myself around vim in general, and the last couple of days are bit blurred to me in regards to which changes happened when. 

Is there a way I can debug this to provide you with more useful input? 

I have updated the description, to explain better when issue arises.

**Comment by zbirenbaum** [comment]
> I just meant that https://github.com/github/copilot.vim has other changes in these commits:
> 
> * [github/copilot.vim@1a55183](https://github.com/github/copilot.vim/commit/1a55183ef9347d6f420406a3746474b6b9fb9ef5)
> * [github/copilot.vim@49e0348](https://github.com/github/copilot.vim/commit/49e0348bfb913fae63ca5ddb987a8bccd193da86)
> * [github/copilot.vim@a8142d4](https://github.com/github/copilot.vim/commit/a8142d44602f1b3f7b5c03c52b55f8f5d3453bf0)
> * [github/copilot.vim@22fd954](https://github.com/github/copilot.vim/commit/22fd9542e3c47552abab5e685fefd760e4f405b2)
> 
> Since those were not ported over in copilot.lua, that could potentially cause issues.
> 
> That's why I asked if the same issue existed before merging #262 .

I read through those commits and the changes probably don't require implementing on our end. There's a couple of housekeeping changes related to things like variable names, some edits/new messages for the logger, and one or two things that appear to be for debugging telemetry.

> Edit: I think I may be knocking at the wrong door. I think this may be more nvim-cmp related. I will look there and update here once I find out more. Suggestions from the autocomplete (not copilot related) also get stuck.

This is very possible. Do you have ghost text enabled for nvim-cmp? Maybe there's some conflict with copilot ghost text and nvim-cmp ghost text trying to appear.

**Comment by blauweb** [comment]
The issues happens with every cmp suggestion, so I am ruling this plugin out as a source for the issue. I have raised this at the nvim-cmp repo, but the maintainer/s don't seem to have the bandwidth or interest in addressing the issue.
So I am closing this.
Much appreciated for you responsiveness!
