### ISSUE TITLE
module 'copilot_cmp' not found

### ISSUE THREAD

**Issue by pyt0xic** [zbirenbaum/copilot.lua#27]
## Details

I keep getting the following error after installing copilot.lua, I can see copilot in LspInfo so I am not sure what is happening exactly...

- Neovim v0.7.0 (nvChad)
- Ubuntu 20.04 (WSL)
- Fresh setup, config is working on my two of my arch installs

## Error

```
Error executing vim.schedule lua callback: ...im/site/pack/packer/opt/copilot.lua/lua/copilot/init.lua:23: module 'copilot_cmp' not found:
        no field package.preload['copilot_cmp']
        no file './copilot_cmp.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/copilot_cmp.lua'
        no file '/usr/local/share/lua/5.1/copilot_cmp.lua'
        no file '/usr/local/share/lua/5.1/copilot_cmp/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/copilot_cmp.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/copilot_cmp/init.lua'
        no file '/home/x/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/copilot_cmp.lua'
        no file '/home/x/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/copilot_cmp/init.lua'
        no file '/home/x/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/copilot_cmp.lua'
        no file '/home/x/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/copilot_cmp/init.lua'
        no file './copilot_cmp.so'
        no file '/usr/local/lib/lua/5.1/copilot_cmp.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/copilot_cmp.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/x/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/copilot_cmp.so'
stack traceback:
        [C]: in function 'require'
        ...im/site/pack/packer/opt/copilot.lua/lua/copilot/init.lua:23: in function 'setup'
        [string "..."]: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by zbirenbaum** [comment]
Do you have https://github.com/zbirenbaum/copilot-cmp installed?

**Comment by pyt0xic** [comment]
Yes, I went through my config and added everything in one by one and I am no longer getting any errors. Although, I don't seem to be getting any completions...

What would be the best way to confirm? Disabling all other cmp sources?

**Comment by zbirenbaum** [comment]
> Yes, I went through my config and added everything in one by one and I am no longer getting any errors. Although, I don't seem to be getting any completions...
> 
> 
> 
> What would be the best way to confirm? Disabling all other cmp sources?

Interesting. Could you check if copilot is listed in :CmpStatus?

**Comment by zbirenbaum** [comment]
> > Yes, I went through my config and added everything in one by one and I am no longer getting any errors. Although, I don't seem to be getting any completions...
> > 
> > 
> > 
> > What would be the best way to confirm? Disabling all other cmp sources?
> 
> Interesting. Could you check if copilot is listed in :CmpStatus?

If it's not there:
1.If you are using NvChad you will need to write your own cmp config file instead of using the default one, since you will need to add copilot as a source, but you may have done this already.

2. Try running require("copilot_cmp").setup() within the config section of the packer entry for copilot_cmp

**Comment by zbirenbaum** [comment]
Ok I managed to reproduce this on my laptop and I think I know how to fix it for you.  Make your packer install statement for copilot-cmp look like this:

```lua
use {
  "zbirenbaum/copilot-cmp",
  module = "copilot_cmp",
},
```

The one from before had a race condition and I think I made some efficiency improvements or something that caused this.

**Comment by pyt0xic** [comment]
Okay so it was working, then it stopped after the update, tried with the new packer install method but no luck.

Copilot shows in LspInfo and is running but CmpStatus lists it as an unknown source.

**Comment by zbirenbaum** [comment]
> Okay so it was working, then it stopped after the update, tried with the new packer install method but no luck.
> 
> 
> 
> Copilot shows in LspInfo and is running but CmpStatus lists it as an unknown source.

I just pushed half a second ago, can you try to update again? Do you happen to know the commit that worked for you?

**Comment by pyt0xic** [comment]
Just updated, still listed as an unknown source, was working on commit [d8e75ffe184a254e328e0143b3e51a1a4bd53375](https://github.com/zbirenbaum/copilot.lua/commit/d8e75ffe184a254e328e0143b3e51a1a4bd53375).

**Comment by pyt0xic** [comment]
@zbirenbaum okay so I removed some things in my config and it seems to be working now. To be honest I am not sure what I changed exactly, it does seem to take a little while to start working though. Will test some more.

I think we can close this issue as the original problem has been solved, I'll create another if I run into any more snags 👍

**Comment by zbirenbaum** [comment]
> @zbirenbaum okay so I removed some things in my config and it seems to be working now. To be honest I am not sure what I changed exactly, it does seem to take a little while to start working though. Will test some more.
> 
> 
> 
> I think we can close this issue as the original problem has been solved, I'll create another if I run into any more snags 👍 

If you are talking about completion delays make sure you are using getCompletionsCycling. There was an update where I put panel as the default on accident. 

I've noticed an insert enter delay that's a bit of a pain, but I think it's due to how I changed copilot_cmp's recommended loading method to module. The delay is the next thing on my list to fix. 

Sorry about the issues, it should be stable and much faster once I'm finished with optimizations. Unfortunately I needed to push to master so that I could have some input on what I've done so far and see if it causes any issues.

**Comment by pyt0xic** [comment]
No worries man, thanks for all your help and a great plugin. 😄 
I have been trying out panel and I haven't found any bugs, I more meant a delay before the source loads up compared to the other sources. Its a little longer than `getCompletionsCycling`, I think if I loaded `nvim-cmp` at startup it would be unnoticeable. How would I do this for certain file types?

I spend half my time writing `FoxPro` and having copilot alone is better than the native `IntelliSense`, combined with buffer and path completion it is a lot better. I would like to write a LSP server for it at some point, I have `ANTLR` grammar for most of the syntax already.

**Comment by zbirenbaum** [comment]
> No worries man, thanks for all your help and a great plugin. 😄 
> 
> I have been trying out panel and I haven't found any bugs, I more meant a delay before the source loads up compared to the other sources. Its a little longer than `getCompletionsCycling`, I think if I loaded `nvim-cmp` at startup it would be unnoticeable. How would I do this for certain file types?
> 
> 
> 
> I spend half my time writing `FoxPro` and having copilot alone is better than the native `IntelliSense`, combined with buffer and path completion it is a lot better. I would like to write a LSP server for it at some point, I have `ANTLR` grammar for most of the syntax already.

Right now the two plugins are in a bit of a weird place where bridging the functions together is kinda awkward so it's hard to tell where the issue is. I'm trying to force it to load immediately but it's actually not making a difference lol. Might be my neovim build tho. I'll implement a way to force it to load cmp immediately.

Another thing you can try is changing your js version. Copilot officially doesn't support version 18, although it will run (just slower to start and respond). If node --version isn't something like 16.15 which is lts, you can use nvm or something to install the lts version and set it to your default.

**Comment by pyt0xic** [comment]
I am a little unsure whether it is actually copilot causing cmp not to load immediately...
I haven't tested without but with any filetype, the CmpStatus command is not available until I start typing which I assumed was an nvChad/neovim thing(I am pretty new to vim 🤣). 

I am running Node 17.9.1, will try the officially suggested one and update.

Is there any details/logs you would like me to include in the issue?

**Comment by zbirenbaum** [comment]
> I am a little unsure whether it is actually copilot causing cmp not to load immediately...
> 
> I haven't tested without but with any filetype, the CmpStatus command is not available until I start typing which I assumed was an nvChad/neovim thing(I am pretty new to vim 🤣). 
> 
> 
> 
> I am running Node 17.9.1, will try the officially suggested one and update.
> 
> 
> 
> Is there any details/logs you would like me to include in the issue?

I'm pretty certain NvChad loads cmp on insert enter by default. You can override it the same way you would any NvChad plugins' packer parameters. I'm a bit busy for the next hour or two, but if you need help I'm more than happy to.

cmp is heavier than you would think though, and the internal source code for every source I've seen just registers an insert enter autocmd to load no matter what you do.

**Comment by pyt0xic** [comment]
Hmm that does make sense, I will try override it and let you know, I don't think we need to open an issue for this unless you would still like me to?

**Comment by zbirenbaum** [comment]
> Hmm that does make sense, I will try override it and let you know, I don't think we need to open an issue for this unless you would still like me to?

I think it's alright. It's noticeable enough that I won't forget it without an issue post.
