### ISSUE TITLE
Autocompleting suggestion broken after latest Neovim update

### ISSUE THREAD

**Issue by danielpost** [zbirenbaum/copilot.lua#273]
After updating Neovim, I'm getting the following error when trying to autocomplete:

```
E5108: Error executing lua: ...vim/HEAD-0fcbda5/share/nvim/runtime/lua/vim/lsp/util.lua:423: Explicit buffer number is required
stack traceback:
	[C]: in function 'assert'
	...vim/HEAD-0fcbda5/share/nvim/runtime/lua/vim/lsp/util.lua:423: in function 'apply_text_edits'
	...l/share/nvim/lazy/copilot.lua/lua/copilot/suggestion.lua:487: in function <...l/share/nvim/lazy/copilot.lua/lua/copilot/suggestion.lua:445>
```

It is almost definitely related to this change: https://github.com/neovim/neovim/pull/27614, and I think the fix would be to pass the current buffer [here](https://github.com/zbirenbaum/copilot.lua/blob/master/lua/copilot/suggestion.lua#L487), but I don't know enough about Lua to be 100% sure.

**Comment by siblanco** [comment]
hi, you are right,

**Comment by GitMurf** [comment]
I am getting the same problem on Windows 11 fyi.

**Comment by fgheng** [comment]
> I am getting the same problem on Windows 11 fyi. And I can confirm the fix provided by @siblanco works so thank you both!

hello, where add this, I add it to lazy config:

```lua
config = function()
  vim.lsp.util.apply_text_edits({ { range = range, newText = newText } }, vim.api.nvim_get_current_buf(), "utf-16")
end
```
where can I take the params range and newText
