### ISSUE TITLE
Copilot showing the same recommendation twice

### ISSUE THREAD

**Issue by AngeloPavone** [zbirenbaum/copilot.lua#28]
Example:
![image](https://user-images.githubusercontent.com/101136391/173254849-a76fc6a1-4e3e-4c84-ac90-e0b9ff943b41.png)
Plugin List:
![image](https://user-images.githubusercontent.com/101136391/173254919-73197695-319e-49f1-8a60-6df2559ab8b4.png)

**Comment by zbirenbaum** [comment]
> Example:
> 
> ![image](https://user-images.githubusercontent.com/101136391/173254849-a76fc6a1-4e3e-4c84-ac90-e0b9ff943b41.png)
> 
> Plugin List:
> 
> ![image](https://user-images.githubusercontent.com/101136391/173254919-73197695-319e-49f1-8a60-6df2559ab8b4.png)
> 
> 

Are you using getCompletionsCycling or getPanelSolutions? Also if you hover it and preview the full body of the completions is there a slight difference or is it identical?

**Comment by AngeloPavone** [comment]
I was using getCompletionsCycling now im trying getPanelSolutions and i am getting the same thing with the later there are 2 options that are the same and one of them with slightly different whitespace but no actual text is different
![image](https://user-images.githubusercontent.com/101136391/173394871-6889a9db-1370-424e-a85b-23742a878142.png)
![image](https://user-images.githubusercontent.com/101136391/173394913-252b5340-f404-4b4f-b124-148ead0aeb08.png)
![image](https://user-images.githubusercontent.com/101136391/173394939-ff7f57d6-4b38-4e89-b270-42db4ae91dde.png)
sorry for all the images just seems like the best way to demonstrate :laughing:

**Comment by AngeloPavone** [comment]
when using the getCompletionsCycling i get 2 suggestions that look like the first and last suggestions from the last set of pictures which are the same

**Comment by zbirenbaum** [comment]
This should be fixed with the new defaults, make sure you are using getPanelCompletions and let me know if it persists.

**Comment by zbirenbaum** [comment]
I'm gonna close this since I think it's fixed and there hasn't been any activity but feel free to reopen if it persists.
