### ISSUE TITLE
Starting LazyVim with this plugin throws an error

### ISSUE THREAD

**Issue by zjeffer** [zbirenbaum/copilot.lua#280]
`[Copilot] Could not find agent.js (bad install?) : nil`

Thrown from here: https://github.com/zbirenbaum/copilot.lua/blob/f7612f5af4a7d7615babf43ab1e67a2d790c13a6/lua/copilot/client.lua#L167-L170

What could cause this?

```
nvim --version
NVIM v0.10.0-dev-2676+g881f5e5917
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
```

My nvim configuration: https://github.com/zjeffer/nvim

If I run `:Copilot status`, it says Copilot is disabled and throws the error again. Running `:Copilot enable` and then `:Copilot status` again shows Copilot is now enabled and does not throw the error. Restarting nvim throws the error again at startup.

I'm pretty new to Neovim, let me know if you need more info

**Comment by ser** [comment]
It's your broken nvim, it has nothing to copilot.lua. Start from scratch.

**Comment by zjeffer** [comment]
I switched to https://github.com/github/copilot.vim and it seems to work a lot better.

Not sure what was wrong with my config for this plugin, I already started from scratch once. Closing.
