### ISSUE TITLE
Feature: Allow custom GH instance urls to be passed in to auth

### ISSUE THREAD

**Issue by lukigarazus** [zbirenbaum/copilot.lua#296]
I have a custom instance of GH Enterprise, so the default behaviour of using GitHub.com for auth does not work for me, as the code is not recognised.

**Comment by zbirenbaum** [comment]
I've been working on this today but it's a little tricky because I don't have a custom instance to work against so might take a little time. Once I have something I think works could you test it out and see if any errors come up?

**Comment by lukigarazus** [comment]
Of course

**Comment by egemenkopuz** [comment]
I can also help you test it out, just notify us here when you create the branch.

**Comment by zbirenbaum** [comment]
#313 should have added support for this on master.
