### ISSUE TITLE
Error executing lua E114: Missing quote

### ISSUE THREAD

**Issue by bashtoni** [zbirenbaum/copilot.lua#3]
I'm using LunarVim, and I added copilot to my Packer config (`lvim.plugins`) like so:

```
  -- github copilot
  {
    "zbirenbaum/copilot.lua",
    event = "InsertEnter",
    config = function ()
      vim.schedule(function() require("copilot") end)
    end
  },
  {
    "zbirenbaum/copilot-cmp",
    after = {"copilot.lua", "nvim-cmp"},
    config = function ()
      lvim.builtin.cmp.formatting.source_names["copilot"] = ""
      table.insert(lvim.builtin.cmp.sources, {name = "copilot"})
    end
  },
```

When I enter insert mode I get this error message:

```
Error detected while processing InsertEnter Autocommands for "*":
E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m/s
ite/pack/packer/start/packer.nvim/lua/packer/load.lua:142: Vim(source):E5113: Error while calling lua chunk: ...ite/pack/packer/opt/copilot-cmp/lua/copilot_cmp
/init.lua:9: attempt to call field 'nvim_create_autocmd' (a nil value)
stack traceback:
        [C]: in function 'cmd'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
```

**Comment by zbirenbaum** [comment]
You aren't on neovim nightly. You are using .6 so nvim_create_autocmd isn't a function yet.

Try getting a nightly image from the neovim github page or build one from source.

**Comment by zbirenbaum** [comment]
Since it was fast and I think that there was the only place I used it, I added a version check. PackerSync and try again.

**Comment by bashtoni** [comment]
Thanks.  Sadly, I've updated and the only difference seems to be that the error is one line further on:

```
Error detected while processing InsertEnter Autocommands for "*":
E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m/s
ite/pack/packer/start/packer.nvim/lua/packer/load.lua:142: Vim(source):E5113: Error while calling lua chunk: ...ite/pack/packer/opt/copilot-cmp/lua/copilot_cmp
/init.lua:10: attempt to call field 'nvim_create_autocmd' (a nil value)
stack traceback:
        [C]: in function 'cmd'
        ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
```

**Comment by zbirenbaum** [comment]
> Thanks. Sadly, I've updated and the only difference seems to be that the error is one line further on:
> 
> ```
> Error detected while processing InsertEnter Autocommands for "*":
> E5108: Error executing lua ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...m/s
> ite/pack/packer/start/packer.nvim/lua/packer/load.lua:142: Vim(source):E5113: Error while calling lua chunk: ...ite/pack/packer/opt/copilot-cmp/lua/copilot_cmp
> /init.lua:10: attempt to call field 'nvim_create_autocmd' (a nil value)
> stack traceback:
>         [C]: in function 'cmd'
>         ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:165: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:161>
>         [string ":lua"]:1: in main chunk
> ```

Run this in command mode and lmk what it says:
`lua print(vim.fn.has('nvim-0.7'))`

**Comment by bashtoni** [comment]
That command returns 0

Output of nvim --version:

```
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.6.1/redhat-linux-build/config -I/builddir/build/BUILD/neovim-0.6.1/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.6.1/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.6.1/redhat-linux-build/include
Compiled by mockbuild@koji

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by zbirenbaum** [comment]
wait I know this issue. give me one sec

**Comment by zbirenbaum** [comment]
PackerSync try again.

**Comment by bashtoni** [comment]
Thanks, we're getting somewhere!
I now get this error when entering insert mode:

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:262: cmd: expected string, got nil
stack traceback:                                                                                                                                     
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:262: in function 'start'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:802: in function 'start_client'
        ...k/packer/opt/copilot.lua/lua/copilot/copilot_handler.lua:20: in main chunk
        [C]: in function 'require'
        ...im/site/pack/packer/opt/copilot.lua/lua/copilot/init.lua:1: in main chunk
        [C]: in function 'require'
        [string "..."]: in function <[string "..."]:0>
```

**Comment by zbirenbaum** [comment]
> Thanks, we're getting somewhere! I now get this error when entering insert mode:
> 
> ```
> Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:262: cmd: expected string, got nil
> stack traceback:                                                                                                                                     
>         [C]: in function 'error'
>         vim/shared.lua:608: in function 'validate'
>         /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:262: in function 'start'
>         /usr/share/nvim/runtime/lua/vim/lsp.lua:802: in function 'start_client'
>         ...k/packer/opt/copilot.lua/lua/copilot/copilot_handler.lua:20: in main chunk
>         [C]: in function 'require'
>         ...im/site/pack/packer/opt/copilot.lua/lua/copilot/init.lua:1: in main chunk
>         [C]: in function 'require'
>         [string "..."]: in function <[string "..."]:0>
> ```

I think LunarVim installs plugins somewhere different than the default. Can you locate where exactly your plugins are installed and let me know the path?

Then, can you supply the output of `:lua print(vim.fn.stdpath("data"))`

**Comment by bashtoni** [comment]
It seems to be storing them in `$HOME/.local/share/lunarvim/site/pack/packer`

`:lua print(vim.fn.stdpath("data"))` returns `/home/sam/.local/share/nvim`

**Comment by zbirenbaum** [comment]
@bashtoni Just pushed a fix. Set your packer use to look like this:
```
   ["zbirenbaum/copilot.lua"] = {
      "zbirenbaum/copilot.lua",
      event = "InsertEnter",
      config = function ()
         vim.schedule(function()
            require("copilot.copilot_handler").start(vim.fn.expand("$HOME") .. "/.local/share/lunarvim/")
         end)
      end,
   },
```

**Comment by bashtoni** [comment]
Thanks for all your help - that's working now.
