### ISSUE TITLE
How to use updated branch?

### ISSUE THREAD

**Issue by leCoq42** [zbirenbaum/copilot.lua#317]
I see that there's an updated branch named: 'create-pull-request/update-copilot-dist'. But for some reason it's not getting merged with the main branch. Is there a way to set my lazyvim config so that it uses the updated branch instead of the main branch?

**Comment by zbirenbaum** [comment]
I manually check to make sure that the new lsp dist doesn't break anything. At some point it would be nice to update the workflow such that the new dist is auto merged into a dev branch so you can always stay up to date and fall back to the stable one but haven't gotten around to it.

If you want to, you can always go to the plugin directory and checkout that pr using `gh pr checkout $PR_NUMBER`
