### ISSUE TITLE
Error accepting suggestions with multibyte (Cyrillic) characters (`utf-16` -> `utf-8` fixes the issue)

### ISSUE THREAD

**Issue by Galicarnax** [zbirenbaum/copilot.lua#330]
When I type with Cyrillic alphabet, and getting suggestions, pressing the key binding to accept gives this error:
```
Error  02:24:02 PM msg_show.lua_error Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:485: index out of range
stack traceback:
	[C]: in function 'get_line_byte_from_position'
	/usr/share/nvim/runtime/lua/vim/lsp/util.lua:485: in function 'apply_text_edits'
	...l/share/nvim/lazy/copilot.lua/lua/copilot/suggestion.lua:489: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
Looking into `lua/copilot/suggestion.lua`, I see this:
```
    vim.lsp.util.apply_text_edits({ { range = range, newText = newText } }, vim.api.nvim_get_current_buf(), "utf-16")
```
If I change `utf-16` to `utf-8`, everything seems to work fine. Any reason for `utf-16` here?

**Comment by traysh** [comment]
I'm having the same problem when I have any accents in the line I'm accepting the suggestion, such as `é` or `ö`. I'm on linux, the default encoding is `utf-8`.

**Comment by traysh** [comment]
[This PR](https://github.com/zbirenbaum/copilot.lua/pull/336) should fix it.
