### ISSUE TITLE
Can not get any suggestions from copilot.lua

### ISSUE THREAD

**Issue by TMTBO** [zbirenbaum/copilot.lua#36]
I just Can not get any suggestions on `nvim-cmp`. And after I do some debug on it, I find that is a problem from `copilot.lua`.
`handles.lua` The next functions can not be called.
```
local handlers = {
  ["PanelSolution"] = function (_, result, _, config)
    print("handlers PanelSolution")
    if not result then return "err" end
    if result.panelId and config.callbacks[result.panelId] then
      config.callbacks[result.panelId](result)
    elseif not config.callbacks[result.panelId] and result.panelId then
      return
    else
      for _, callback in pairs(config.callbacks) do callback() end
    end
  end,

  ["PanelSolutionsDone"] = function (_, _, _, config)
    print("handlers PanelSolutionsDone")
    for _, callback in pairs(config.callbacks) do
      callback()
    end
  end
}
```

I can got one suggestion in placeholder, but not in `nvim-cmp` window.
<img width="795" alt="image" src="https://user-images.githubusercontent.com/2801001/174743613-878185d3-e0a8-4275-bc34-f603698a1e4e.png">

ENV:
nvim: v0.7.0
os: macos 12.4

**Comment by zbirenbaum** [comment]
This may be related to the brand new changes to copilot since microsoft is moving to a paid model. Check if copilot is enabled in your github. 

If it set up properly already, or copilot.vim works without issue, please supply the output of CmpStatus and LspInfo

**Comment by TMTBO** [comment]
Yeah, copilot.vim works correctly.
<img width="693" alt="image" src="https://user-images.githubusercontent.com/2801001/174926038-8647d788-d107-4253-9c27-66885b1826b1.png">

The output of  CmpStatus and LspInfo:
<img width="863" alt="image" src="https://user-images.githubusercontent.com/2801001/174926074-d69523b2-7539-4866-9d73-d53aa425a6d2.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/2801001/174926108-dc9e5297-a8f5-4b30-8ab3-7f26827d9f54.png">

**Comment by ouuan** [comment]
I made it work by replacing `copilot/dist` with the one in the official copilot.vim

**Comment by zbirenbaum** [comment]
> I made it work by replacing `copilot/dist` with the one in the official copilot.vim

That's very interesting, mine still works somehow. I'll go ahead and update it, thanks for letting me know.

**Comment by zbirenbaum** [comment]
I've replaced it with the most up to date version. Let me know if that fixes it.

The one prior to this had no real changes, the packing tool just altered the variable names and I think they added some telemetry stuff so I didn't update. Since it went paid today they likely changed some things in there that caused a version conflict.

**Comment by TMTBO** [comment]
Ok, I made it works by disable copilot.vim. And close ths issue.
