### ISSUE TITLE
Remove possible closing bracket (or whatever closing pair)

### ISSUE THREAD

**Issue by abenz1267** [zbirenbaum/copilot.lua#43]
Hi,

i'm facing following minor annoyance and i was wondering, if that's something this plugin COULD fix, or i need to find another solution:

so i'm using nvim-autopairs.... and with copilot snippets this can be a bit annoying. f.e.

```go
someFunc(|)
```

and the copilot suggestion might already contain a closing bracket, so you end up with

```go
someFunc(copilotsuggestion))
```

and you now need to remove the extra closing bracket. That's midly annoying.

Any idea how to avoid this?

Regards

**Comment by y9c** [comment]
Thanks @zbirenbaum . Is there a way to fix this manually?

**Comment by zbirenbaum** [comment]
Set remove_after_cursor in the copilot-cmp options to true. It will be the default soon, but I left it as opt-in to start so I’d have a chance make sure nothing broke. Sorry for not getting back about this, I resolved it in copilot-cmp but forgot to post and close here.

**Comment by y9c** [comment]
Hi @zbirenbaum, could you send me the link to `remove_after_cursor` option? I can not find this setting within `copilot-cmp` repo.

**Comment by y9c** [comment]
Found it. Should be `clear_after_cursor`.  Thanks.

**Comment by zbirenbaum** [comment]
> Found it. Should be `clear_after_cursor`. Thanks.

Oops, sorry I was on mobile and messed that up. I fixed it in my comment case anyone finds this issue and gets confused

**Comment by matthewsia98** [comment]
Is there no fix if not using `copilot-cmp`?
