### ISSUE TITLE
Getting a module 'copilot-cmp' not found with packer

### ISSUE THREAD

**Issue by cs-clarence** [zbirenbaum/copilot.lua#45]
Here's the config that I used
```lua
{
  "zbirenbaum/copilot.lua",
  event = { "VimEnter" },
  config = function()
    vim.defer_fn(function()
      print("copilot enter")
      require("copilot").setup()
    end, 100)
  end,
},
{
  "zbirenbaum/copilot-cmp",
  after = { "copilot.lua" },
  config = function()
    print("copilot cmp enter")
    require("copilot-cmp").config()
  end,
},
```

Here's the error that I got
```
packer.nvim: Error running config for copilot-cmp: [string "..."]:0: module 'copilot-cmp' not found:
^Ino field package.preload['copilot-cmp']
^Ino file './copilot-cmp.lua'
^Ino file '/usr/share/luajit-2.1.0-beta3/copilot-cmp.lua'
^Ino file '/usr/local/share/lua/5.1/copilot-cmp.lua'
^Ino file '/usr/local/share/lua/5.1/copilot-cmp/init.lua'
^Ino file '/usr/share/lua/5.1/copilot-cmp.lua'
^Ino file '/usr/share/lua/5.1/copilot-cmp/init.lua'
^Ino file './copilot-cmp.so'
^Ino file '/usr/local/lib/lua/5.1/copilot-cmp.so'
^Ino file '/usr/lib64/lua/5.1/copilot-cmp.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by zbirenbaum** [comment]
Use `require("copilot-cmp").setup()` instead of `require("copilot-cmp").config()` and include either `after = { "copilot.lua", "nvim-cmp "},` or `module = "copilot_cmp"` so it isn't called by nvim-cmp before it's loaded.

Realistically speaking, you can start it before copilot.lua, since all calling setup does is make an InsertEnter autocmd for the real setup, and there are checks in place to make sure the copilot server is on. I should probably do some testing  to ensure no possible errors and change the docs.

**Comment by cs-clarence** [comment]
> Use `require("copilot-cmp").setup()` instead of `require("copilot-cmp").config()` and include either `after = { "copilot.lua", "nvim-cmp "},` or `module = "copilot_cmp"` so it isn't called by nvim-cmp before it's loaded.
> 
> Realistically speaking, you can start it before copilot.lua, since all calling setup does is make an InsertEnter autocmd for the real setup, and there are checks in place to make sure the copilot server is on. You might just not get completions until you go back to normal mode and then enter insert mode again if copilot server starts after the fact.

Replaced `config` with `setup` but the error is still there. I'm not sure if this is an error with packer or this plugin.

**Comment by cs-clarence** [comment]
I changed the require to "copilot_cmp" instead of "copilot-cmp", now it works. The example codes in this repository uses "copilot-cmp" so I don't know why this worked.

**Comment by CharlesChiuGit** [comment]
> I changed the require to "copilot_cmp" instead of "copilot-cmp", now it works. The example codes in this repository uses "copilot-cmp" so I don't know why this worked.

This helps! Thanks!

**Comment by zbirenbaum** [comment]
So sorry about that, I've updated the docs
