### ISSUE TITLE
Copilot not running without the official Copilot plugin

### ISSUE THREAD

**Issue by vizmoe** [zbirenbaum/copilot.lua#57]
When I uninstall Topre's plugin and install copilot.lua and copilot-cmp by packer.nvim. I cannot run :CopilotAuth normallly. It reminds me "Copilot not running yet.". I have to add github/copilot.vim again to make it work.

```lua
lvim.plugins = {
  {
    "github/copilot.vim",
    config = function()
      vim.g.copilot_no_tab_map = true
      vim.g.copilot_assume_mapped = true
    end
  },
  {
    "hrsh7th/cmp-copilot",
    after = { "copilot.vim", "nvim-cmp" },
    config = function()
      lvim.builtin.cmp.formatting.source_names["copilot"] = "(Cop)"
      table.insert(lvim.builtin.cmp.sources, { name = "copilot" })
    end
  },
  {
    "zbirenbaum/copilot.lua",
    event = { "VimEnter" },
    config = function()
      vim.defer_fn(function()
        require("copilot").setup()
      end, 100)
    end,
  },
```

**Comment by zbirenbaum** [comment]
This is a problem with lunarvim changing where packages are installed. Check the readme section on `plugin_manager_path` to see how to use the option and then supply the correct path.

**Comment by vizmoe** [comment]
Thanks for your reply, I have fixed the problem with the below configuration.

  {
    "zbirenbaum/copilot.lua",
    event = { "VimEnter" },
    config = function()
      vim.defer_fn(function()
        require("copilot").setup {
          -- LunarVim users need to specify path to the plugin manager 
          plugin_manager_path = os.getenv "LUNARVIM_RUNTIME_DIR" .. "/site/pack/packer",
        }
      end, 100)
    end,
  },
  {
    "zbirenbaum/copilot-cmp",
    after = { "copilot.lua" },
    config = function()
      require("copilot_cmp").setup()
    end
  },

**Comment by y9c** [comment]
I have the same problem with one of the servers, while packer is install in the default path (vim.fn.stdpath("data") .. "/site/pack/packer")

**Comment by y9c** [comment]
It is relative to nodejs version. Upgrade to version 16 fix the problem.

**Comment by zbirenbaum** [comment]
I put a node version disclaimer 3 places in the readme, including in the config args, but I still see people having issues with it weekly it seems like. 

Is there anything that I could change about the readme that you think would have made it clearer/more apparent what the problem was? Or do you have any other advice for what I could do that would have helped you find the problem sooner? @y9c

**Comment by y9c** [comment]
Thanks @zbirenbaum. I did use node v16. I think there is something wrong with my node installation. It works well in most of my computer, expect the one with wls2 installed. After reinstall nodejs, the problem was disappeared.
