### ISSUE TITLE
error running config in lunarvim

### ISSUE THREAD

**Issue by mhuggins7278** [zbirenbaum/copilot.lua#65]
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/1205776/195345807-bc2bbc91-41d7-4797-bab1-34b9839e787c.png"> 

my plugin config 
```lua
	{
		"zbirenbaum/copilot.lua",
		event = { "VimEnter" },
		config = function()
			vim.defer_fn(function()
				require("copilot").setup({
					plugin_manager_path = "/Users/MHuggins/.local/share/lunarvim/site/pack/packer"
				})
			end, 100)
		end,
	},

```

**Comment by MunifTanjim** [comment]
I'm not sure how Lunarvim sets everything up, but did you try running `:PackerCompile` after updating your config?

**Comment by mhuggins7278** [comment]
when i was refactoring some stuff in my config i added a local vim = vim in my plugins.lua i just need to use the globals and deal with the linter errors
