### ISSUE TITLE
Not getting suggestions for some languages

### ISSUE THREAD

**Issue by yngwi** [zbirenbaum/copilot.lua#69]
Hi,

I'm not getting suggestions when using copilot.lua and copilot.cmp for some languages. I'm not sure what the difference is, `Copilot status` lists `Online` and `Enabled for typescriptreact` (for instance for a `*.tsx` file). Languages (that I tried) that work are rust, php, css, what don't are javascript/typescript, python. If I remember correctly, all languages worked at some point.

I'm not sure what I can do to narrow down the problem.

Best,
Daniel

**Comment by CharlesChiuGit** [comment]
For me, copilot does work in python.
![image](https://user-images.githubusercontent.com/32497323/195551403-ce26321d-c832-498d-98aa-48d43b62c7af.png)

**Comment by MunifTanjim** [comment]
I'm not sure about `copilot-cmp`, but `javascript`, `javascriptreact`, `typescript`, `typescriptreact`, `python` all of them are working for me with `copilot.lua`. 🤔

How are you using copilot, btw? Is it just with `nvim-cmp`? Or are you using `copilot.lua`'s suggestion and panel also?

**Comment by zbirenbaum** [comment]
I can confirm typescript and JavaScript seem to be working fine with copilot-cmp. Please make sure your node version is <= 16.x.x

**Comment by yngwi** [comment]
Thank you for this information, it was indeed that I had installed node > 16. After changing it, everything works!

**Comment by yngwi** [comment]
@zbirenbaum Sorry to come back to this but are there any plans to update to newer Node.js versions? Node version 18 is [now](https://nodejs.org/en/blog/release/v18.12.0/) the current LTS version which means other, older versions are more difficult to install for users, for instance using scoop on Windows only supports current and LTS versions.

**Comment by zbirenbaum** [comment]
> @zbirenbaum Sorry to come back to this but are there any plans to update to newer Node.js versions? Node version 18 is [now](https://nodejs.org/en/blog/release/v18.12.0/) the current LTS version which means other, older versions are more difficult to install for users, for instance scoop on Windows only supports current and LTS versions.

Ask Microsoft. I’d love to have support for 18 but the copilot agent is closed source so we are at their mercy. I wouldn’t get your hopes up. Use nvm and install node 16 just for copilot, then point the config option for the copilot node command at that executable and you can still use 18 as your default.

**Comment by yngwi** [comment]
Thank you for the reply. I didn't realize that this is something that Microsoft has to do. Of course, I know how to handle having multiple versions on my system I was just wondering how this would be handled in the future. Sorry if this sounded demanding, I'm very grateful for your great plugins!

**Comment by zbirenbaum** [comment]
> Thank you for the reply. I didn't realize that this is something that Microsoft has to do. Of course, I know how to handle having multiple versions on my system I was just wondering how this would be handled in the future. Sorry if this sounded demanding, I'm very grateful for your great plugins!

No problem at all! I'm sorry if I came across a little blunt there, Microsoft's decision making around copilot has been a point of frustration for me as well, so a bit of that may have come across in my comment, but it wasn't directed towards you in the slightest. Believe me, I'm on your side here, having node 18 support would be awesome for so many reasons, and I really don't think it should be that hard to implement on their end. Unfortunately, I would be pretty surprised if they got around to it before the next LTS version of node is released...

**Comment by yngwi** [comment]
No worries, as I said, I highly appreciate your work!
