### ISSUE TITLE
Error running config for copilot:lua... Attempt to to index upvalue ''

### ISSUE THREAD

**Issue by lucax88x** [zbirenbaum/copilot.lua#7]
Was avid copilot user in the past months, so it was working correctly.

I uninstalled the vim version and installed yours, but I'm experiecing this error as soon as I insert any char as I am using event Insert as you specified in the docs.

![2022-04-05_13-33](https://user-images.githubusercontent.com/6294464/161744951-e989a653-b340-4b97-9dca-37369c85712a.png)

What I'm doing wrong?

**Comment by zbirenbaum** [comment]
Hi, can you show me the config you have for copilot.lua in your `use` code? This looks like an issue with the config you have set up.

**Comment by lucax88x** [comment]
exactly same code in your README.MD

```
		use({
			"zbirenbaum/copilot.lua",
			event = "InsertEnter",
			config = function()
				vim.schedule(function()
					require("copilot").setup()
				end)
			end,
		})
```

**Comment by zbirenbaum** [comment]
> exactly same code in your README.MD
> 
> 
> 
> ```
> 
> 		use({
> 
> 			"zbirenbaum/copilot.lua",
> 
> 			event = "InsertEnter",
> 
> 			config = function()
> 
> 				vim.schedule(function()
> 
> 					require("copilot").setup()
> 
> 				end)
> 
> 			end,
> 
> 		})
> 
> ```

This is very strange. What version of neovim are you using?

**Comment by lucax88x** [comment]
Nightly. yeah. I don't understant that.

**Comment by zbirenbaum** [comment]
> Nightly. yeah. I don't understant that.

There definitely shouldn't be any issues then. Have you tried updating with packer sync? Worst case you might try nuking the plugin dir and reinstalling with a packer sync in case I commit --amend'd and it's not pulling an update

**Comment by lucax88x** [comment]
Yes, I even tried removing  ~/local/.share/nvim/site and ~/.cache/nvim/packer but nah, nothing fixes the issue, that's so weird.

Maybe I need to del some other folder?

https://github.com/lucax88x/configs/tree/master/dotfiles/.config/nvim

that's my dotfiles ..

**Comment by zbirenbaum** [comment]
I looked through your dot files. The copilot config seems to require something called lt.plugins.copilot-lua

I didn't see such a file there, and if that's where packer is set to install plugins, it should be require("copilot").setup()

**Comment by lucax88x** [comment]
Ops, I forgot to push, check it now.

**Comment by zbirenbaum** [comment]
Something I just thought of, do you install plugins to a non-standard location?

**Comment by lucax88x** [comment]
Removing the vim.schedule function fixed the problem.... Dunno why. I never used it anyway.
