### ISSUE TITLE
Don't mess with `InsertEnter` event when inserting suggestions

### ISSUE THREAD

**Issue by mystilleef** [zbirenbaum/copilot.lua#72]
I just switched from `copilot.vim` and I notice whenever I accept a suggestion `copilot.lua` temporarily toggles the `InsertEnter` event. Unfortunately, this kicks me out of `Zen Mode` and also randomly highlights the buffer.

The `copilot.vim` approach of inserting suggestions without messing the `InsertEnter` event is far more preferable and less disruptive, especially for plugins or features that rely on the `InsertEnter` state to work, like my custom `Zen Mode` feature.

Can you adopt the `copilot.vim` approach? 

I also notice that after inserting suggestions, the cursor is placed on the last character of the suggestion instead of after it. Is there a way to change this behavior?

I don't use `nvim-cmp`. Here's my settings.

```lua
local status_ok, copilot = pcall(require, "copilot")

if not status_ok then
  return
end

local home = vim.fn.expand("$HOME")

copilot.setup({
  filter = { ["."] = false },
  suggestion = {
    debounce = 1000,
    auto_trigger = true,
    keymap = {
      accept = "<tab>",
      next = "<c-j>",
      prev = "<c-k>",
      dismiss = "<c-\\>",
    },
  },
  copilot_node_command = home .. "/.nvm/versions/node/v16.15.0/bin/node",
})
```

**Comment by MunifTanjim** [comment]
Hey @mystilleef, I don't have access to your "custom Zen Mode feature"... but based on your description, I opened this PR: https://github.com/zbirenbaum/copilot.lua/pull/73

Can you please test if that fixes the issue for you?

**Comment by MunifTanjim** [comment]
> I also notice that after inserting suggestions, the cursor is placed on the last character of the suggestion instead of after it. Is there a way to change this behavior?

You can disable the default keymap:

```lua
copilot.setup({
  -- ...
  suggestion = {
    -- ...
    keymap = {
      accept = false,
      -- ....
    },
  },
  -- ..
})
```
    
And set custom keymap like this:

```lua
vim.keymap.set("i", "<tab>", function()
    require("copilot.suggestion").accept()
    -- Put cursor on next line.
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Enter>", true, false, true), "n", false)
end, {
  desc = "[copilot] accept suggestion",
  silent = true,
})
```

**Comment by mystilleef** [comment]
@MunifTanjim, fantastic work! 

PR #73 fixes both issues. 

You can close this after the merge.

Thank you!
