### ISSUE TITLE
Latest version throws out copilot info

### ISSUE THREAD

**Issue by olimorris** [zbirenbaum/copilot.lua#76]
Upgrading the latest version, I notice that the following is output upon Copilot loading:

```lua
{
  editorConfiguration = {
    disabledLanguages = { ".", "cvs", "gitcommit", "gitrebase", "help", "hgcommit", "markdown", "svn", "yaml" },
    enableAutoCompletions = true
  },
  editorInfo = {
    name = "Neovim",
    version = "0.8.0 + Node.js 19.0.1"
  },
  editorPluginInfo = {
    name = "copilot.vim",
    version = "1.6.1"
  }
}
```

Reading both `Copilot.vim` and `Copilot.nvim`, I'm not sure how we disable this.

**Comment by CharlesChiuGit** [comment]
Notice this too.

**Comment by rebelot** [comment]
@olimorris no way to disable it, it's probably a debug print that will be resolved quickly

https://github.com/zbirenbaum/copilot.lua/blob/46b28e39d66a7c2275239791429dc7e0ecfb2471/lua/copilot/client.lua#L63

**Comment by CharlesChiuGit** [comment]
@MunifTanjim

**Comment by MunifTanjim** [comment]
Sorry about that. Forgot to remove it.

Pull the latest changes, it's removed now.

**Comment by CharlesChiuGit** [comment]
Thanks!
