### ISSUE TITLE
Can't re-authenticate.

### ISSUE THREAD

**Issue by beauwilliams** [zbirenbaum/copilot.lua#84]
I'm getting spammed with messages that my preview expired. I need to sign out and in to get paid plan working.

But it seems I can't remove old token. How can I sign out, or where is token stored on machine?

Copilot.vim offers signout function

Issue from copilot here --> https://github.com/community/community/discussions/39533

**Comment by zbirenbaum** [comment]
Just `rm ~/.config/github-copilot/hosts.json` and the next time you will fully reauth.

There's a signout function in copilot.auth, does it not do what you are looking for?

**Comment by beauwilliams** [comment]
Thanks! I found it. I was digging through the code all good. Was trying `Copilot signout` same as compilot.vim

But it gives me `Unknown params: signout` I realised I needed `Copilot auth signout` - my bad.

Seems that copilot auth is broken. Upstream issue. So closing for now.
