### ISSUE TITLE
[copilot] config is already set

### ISSUE THREAD

**Issue by LegendaryPredz** [zbirenbaum/copilot.lua#94]
>[copilot] config is already set
Error executing vim.schedule lua callback: ...ite/pack/packer/start/copilot.lua/lua/copilot/client.lua:47: attempt to index local 'params' (a nil value)
stack traceback:
        ...ite/pack/packer/start/copilot.lua/lua/copilot/client.lua:47: in function 'merge_server_opts'
        ...ite/pack/packer/start/copilot.lua/lua/copilot/client.lua:76: in function 'start'
        .../site/pack/packer/start/copilot.lua/lua/copilot/init.lua:37: in function <.../site/pack/packer/start/copilot.lua/lua/copilot/init.lua:36>

I'm not sure why I'm getting  this error. It says that the config is already set but I'm not sure where I'm going wrong.

#### plugins.lua
```lua
lvim.plugins = {
	"cpea2506/one_monokai.nvim",
	{
		"navarasu/onedark.nvim",
		require("onedark").setup({
			style = "warmer",
		}),
	},
	"sainnhe/edge",
	"p00f/nvim-ts-rainbow",
	"windwp/nvim-ts-autotag",
	"kylechui/nvim-surround",
	"NvChad/nvim-colorizer.lua",
	"lvimuser/lsp-inlayhints.nvim",
	"jose-elias-alvarez/typescript.nvim",
	"mxsdev/nvim-dap-vscode-js",
	"petertriho/nvim-scrollbar",
	-- "j-hui/fidget.nvim",
	"folke/todo-comments.nvim",
	"nvim-treesitter/playground",
	"nvim-treesitter/nvim-treesitter-textobjects",
	"christianchiarulli/harpoon",
	"hrsh7th/cmp-emoji",
	"renerocksai/telekasten.nvim",
	"renerocksai/calendar-vim",
	{ "tzachar/cmp-tabnine", run = "./install.sh" },
	{
		"zbirenbaum/copilot.lua",
		-- event = { "VimEnter" },
		config = function()
			vim.defer_fn(function()
				require("copilot").setup({
					plugin_manager_path = os.getenv("LUNARVIM_RUNTIME_DIR") .. "/site/pack/packer",
				})
			end, 100)
		end,
	},
	{
		"zbirenbaum/copilot-cmp",
		after = { "copilot.lua" },
		config = function()
			require("copilot_cmp").setup({
				formatters = {
					insert_text = require("copilot_cmp.format").remove_existing,
				},
			})
		end,
	},
}
```

**Comment by MunifTanjim** [comment]
Are you using the latest versions of plugin? And are you sure you're not doing `require("copilot").setup()` from anywhere else?

**Comment by LegendaryPredz** [comment]
I'm not sure what changed but after restarting my computer the error ceases to show up.

**Comment by LegendaryPredz** [comment]
I've checked and have currently not found anywhere where I call `require("copilot").setup()` another time. I've also tried removing `vim.defer_fn` as well but to no avail. 

It seems that copilot is working as I'm getting recommendations in nvim-cmp, but the error continues to appear.

**Comment by MunifTanjim** [comment]
I can reproduce this by calling `:PackerSync` manually. Maybe `lvim` is doing it automatically on every startup.
