### ISSUE TITLE
Copilot panel empty suggestions? 

### ISSUE THREAD

**Issue by Avi-D-coder** [zbirenbaum/copilot.lua#97]
I'm on the latest version, and I'm using the cmp plugin which works great.

Is this behavior expected?
I sometimes see suggestions when I open the panel, but often I only get one far down the list or none at all.
All 10 entries (copilot id, score) are listed, but many entries don't show the text of the suggestion (). If I call `lua require("copilot.panel").accept()` It inserts the hidden suggestion. So I cannot see the suggested text until I accept it.

![image](https://user-images.githubusercontent.com/29133776/209005667-9540ca5b-015a-4a2e-b427-1d08cfd6aadb.png)

Also `panel.keymap.{accept, refresh}` bindings are not working anymore. I'm not sure when they broke or if it's related.

**Comment by MunifTanjim** [comment]
What's your Neovim version?

Is this only happening on Rust codebases? Or any codebases?

**Comment by Avi-D-coder** [comment]
Any codebase.
```
❯ nvim --version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"
```

**Comment by zbirenbaum** [comment]
Is it at all possible this is a highlighting issue? It's very strange that the text exists since its being inserted but isn't showing. Normally if there was some conflict between copilot-cmp and the panel you wouldn't get anything at all.

The other thing I would recommend trying is disabling copilot-cmp briefly. If the panel starts working we will know generally what the problem is and I can write a bridge between the two plugins to resolve it.

**Comment by Avi-D-coder** [comment]
Treesitter is up to date.
No difference without `copilot-cmp`.

Also note that some suggestions do show up correctly. My prior screen shot only showed hidden suggestions, here's one with both hidden and correctly shown suggestions:

![image](https://user-images.githubusercontent.com/29133776/209573468-79f9a4f6-166c-4fb7-8469-254795a280fd.png)

**Comment by raine** [comment]
I'm seeing the same issue. Not using `copilot-cmp`.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/11027/213889800-4dcaba2f-20ac-42b0-8adb-f8927d8e555e.png">

I tried quickly in another filetype and I can see something so I think that rules out highlighting issue.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/11027/213889927-e8afc59c-d06c-4635-8efb-143e6b4cf491.png">

**Comment by thenbe** [comment]
I've been experiencing this bug for a few months now. I may have noticed a pattern of what triggers this behavior.

Opening the copilot panel when your cursor is at the beginning of the line = good (results viewable in panel almost consistently)

Opening the copilot panel when your cursor is not at the beginning of the line (i.e. indented) = flaky (results hidden in panel)

If you're experiencing the same issue, does what I just stated hold true for you? If so, then perhaps this could this be related to indentation options/plugins?

**Comment by MunifTanjim** [comment]
@thenbe Thanks! That was extremely helpful.
